### ISSUE TITLE
Redpanda Quickstart setup instructions for Console need some additional bootstrapping detail for finding brokers.

### ISSUE THREAD

**Issue by hcoyote** [redpanda-data/documentation#1003]
### Describe the Issue

The instructions for setting up a helm-based console using the quick start instructions results in a failing console startup because we don't give the specific bootstrapping in the doc required to find the brokers. As written, the user is expected to dig around in the values.yaml or helm chart configuration to wire it up. This makes it difficult for inexperienced implementers to know how to proceed.

Fixing this would make it easier for inexperienced implementers to come up to speed during their run through of the quickstart.

### Updates to existing documentation

https://docs.redpanda.com/docs/platform/quickstart/console-installation/#kubernetes

In the Kubernetes section, we should consider providing example snippets for the user to configure the brokers in either the values.yaml or in the helm chart config. If pointing people to use the values.yaml, I presume the snippet would end up in the following chunk of the file, but it's not clear what that snippet would look like.

```
console:
  # Config.yaml is required for Console
  # See reference config: https://github.com/redpanda-data/console/blob/master/docs/config/console.yaml)
  config: {}
  # roles:
  # roleBindings:
```
An alternative is to have them wire this up during the `helm install` command with something like the following:

```
helm install redpanda-console/console --namespace redpanda --generate-name --set 'console.config.kafka.brokers={redpanda-0.redpanda.redpanda.svc.cluster.local.:9093}'
```

The above would require us showing them how to find the broker names, so an additional `rpk` command would likely be needed in the steps. 

### If the requested update is from customer feedback or a Community slack conversation, provide a link:

This is feedback from the internal slack that I asked about while doing my first-week onboarding. I was testing the quickstart with 22.3.9.

**Comment by hcoyote** [comment]
also, somewhat related: 

the current helm install for console isn't clear on if we can/should/need to put the console into the redpanda namespace, and my poking around in Slack didn't come with a clear reason _not_ to.

This is why my suggested command has `--namespace redpanda --generate-name`. It's probably worth confirming that this isn't a horrible idea before sticking it in the docs as well.

**Comment by Feediver1** [comment]
@JakeSCahill FYI - this should be factored in to your updates for the new Redpanda Quickstart - Console installation should be a standard part of RP installs.
