### ISSUE TITLE
Ballast File missing command execution

### ISSUE THREAD

**Issue by r-vasquez** [redpanda-data/documentation#1012]
### Describe the Issue

Our current ballast file documentation displays the required configurations needed to create the ballast file via rpk, but it's missing the command execution to actually create the file:

`rpk redpanda tune ballast_file`

### Updates to existing documentation
https://docs.redpanda.com/docs/platform/deployment/disk-utilization/#create-a-ballast-file

**Comment by vuldin** [comment]
So the above command needs to be ran in spite of `tune_ballast_file: true`? If so, what does this parameter control? The docs say "Set to true to enable ballast file creation. Default is false."
