### ISSUE TITLE
Clarify rpk installation on MacOS

### ISSUE THREAD

**Issue by r-vasquez** [redpanda-data/documentation#1017]
### Describe the Issue

For Mac OS we have 2 ways of installing redpanda:
1. Using homebrew: `brew install redpanda-data/tap/redpanda.`
2. Manually downloading the binary.

The better UX, in most cases, is to run (1) and leave (2) for special cases, however, we only document the homebrew(1) approach under [`Installation and Upgrade > Install Redpanda > macOS #Install rpk` ](https://docs.redpanda.com/docs/platform/quickstart/quick-start-macos/) but we don't mention this alternative in [`Install and Upgrade > Install rpk #macOS`](https://docs.redpanda.com/docs/platform/quickstart/rpk-install/).

### Updates to existing documentation

What I suggest is having the [`Installation and Upgrade > Install Redpanda > macOS #Install rpk` ](https://docs.redpanda.com/docs/platform/quickstart/quick-start-macos/)  page link to the manual installation, something like:

```md
## Install RPK

- Install from Homebrew:
  $ brew install redpanda-data/tap/redpanda

- Manually download the rpk binary #(Link to https://docs.redpanda.com/docs/platform/quickstart/rpk-install/)
```

And inside [`Install and Upgrade > Install rpk #macOS`](https://docs.redpanda.com/docs/platform/quickstart/rpk-install/). we can do something like:

![image](https://user-images.githubusercontent.com/59714880/212120431-3c47ded4-a4ab-40eb-8c78-bbc1ba52d1f1.png)

Just in case someone lands here directly.

**Comment by Feediver1** [comment]
@JakeSCahill Already covered in your new RP QS? If so, you can mark as a duplicate and close. If not, please ensure the new QS reflects this before merging. Thx!

**Comment by JakeSCahill** [comment]
I think this change should be reflected in the `rpk-install` doc. For the quickstart, we should be opinionated and provide the better UX, which as @r-vasquez says is the `brew install....`.

We can leave this one open and make the change to `rpk-install`.

**Comment by JakeSCahill** [comment]
In fact, if @Deflaimun incorporates these changes, we can single-source it in the quickstart.
