### ISSUE TITLE
Docker Compose doesn't work for Mac M1

### ISSUE THREAD

**Issue by JakeSCahill** [redpanda-data/documentation#1031]
### Describe the Issue

When you try to run the [sample Docker Compose for Redpanda Console](https://docs.redpanda.com/docs/platform/console/reference/docker-compose/) on macOS M1 machines, you get the following errors:

```
 ⠧ connect The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested   0.0s
 ⠧ owl-shop The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested  0.0s
```

The solution seems to be to specify the platform:

```yaml
  owl-shop:
    platform: 'linux/amd64'
  connect:
    platform: 'linux/amd64'
```

@weeco is this what we should advise users to do or should we offer these images for different platforms like we do for Redpanda and Redpanda Console?

### Updates to existing documentation

https://docs.redpanda.com/docs/platform/console/reference/docker-compose/

**Comment by weeco** [comment]
> @weeco is this what we should advise users to do or should we offer these images for different platforms like we do for Redpanda and Redpanda Console?

Ideally we should offer multi-platform images.
