### ISSUE TITLE
cert script should be moved out of personal gist

### ISSUE THREAD

**Issue by micheleRP** [redpanda-data/documentation#1045]
### Describe the Issue

Encryption page has a link to a Juan's personal gist: https://gist.github.com/0x5d/30404e0b3376a3724da828f1db5a3b1d29ffebf5

Script should be moved somewhere else. 

### Updates to existing documentation

https://docs.redpanda.com/docs/manage/security/encryption/ 

### Additional notes

Juan is asking an admin to create a new gist for the script.

**Comment by micheleRP** [comment]
See https://redpandadata.slack.com/archives/CPKP64GDN/p1673994177820299

**Comment by Feediver1** [comment]
@0x5d  
Not sure if this is a doc or code issue? Docs sends users to your gist link, but what if the link gets revised to no longer be public? Shouldn't the script we send RP customers to for generating CAs be in `redpanda-data` and not a personal git gist? Please advise. Thx.
