### ISSUE TITLE
Kubernetes Operator Quickstart instructions do not work

### ISSUE THREAD

**Issue by tmgstevens** [redpanda-data/documentation#1062]
### Describe the Issue

I tried building a cluster this morning based on the Operator guide and the end-to-end EKS instructions do not work. The cluster will not deploy pods because they are unable to create the gp2 storage.

### Updates to existing documentation

https://docs.redpanda.com/docs/reference/redpanda-operator/kubernetes-qs-cloud/

**Comment by JakeSCahill** [comment]
@tmgstevens this seems like it's the same issue we had with Helm installations. Can you confirm whether adding the EBS CSI add-on solves the issue?

1. Create the IAM role needed for the Amazon Elastic Block Store (EBS) Cluster Storage Interface (CSI):
```
eksctl create iamserviceaccount \
    --name ebs-csi-controller-sa \
    --namespace kube-system \
    --cluster redpanda \
    --attach-policy-arn arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy \
    --approve \
    --role-only \
    --role-name AmazonEKS_EBS_CSI_DriverRole
```

2. Get your AWS account ID:
```
AWS_ACCOUNT_ID=`aws sts get-caller-identity | jq -r '.Account'`
```

3. Add the EBS CSI add-on:
```
eksctl create addon \
    --name aws-ebs-csi-driver \
    --cluster redpanda \
    --service-account-role-arn arn:aws:iam::${AWS_ACCOUNT_ID}:role/AmazonEKS_EBS_CSI_DriverRole \
    --force
```

**Comment by tmgstevens** [comment]
On step 1 above, I get:
```
Error: unable to create iamserviceaccount(s) without IAM OIDC provider enabled
```

**Comment by JakeSCahill** [comment]
@tmgstevens This is to do with your account setup. The Redpanda AWS accounts use OIDC. This may help you: https://docs.aws.amazon.com/eks/latest/userguide/enable-iam-roles-for-service-accounts.html
