### ISSUE TITLE
Update latest version notes to point to latest version of current page

### ISSUE THREAD

**Issue by Feediver1** [redpanda-data/documentation#1065]
### Describe the Issue

https://redpandadata.slack.com/archives/C01LK3UK2K1/p1674152774708289

How hard would it be to make the "For up-to-date documentation, see the latest version" note point to the latest version of the current page? For example, on this page, clicking the latest version, I would expect the link to take me to the 22.3 version of the Migrating data to Redpanda topic, not to the top-level 22.3 docs. If we could figure out how to do this, I think it would increase the docs usability for the reader, rather than breaking their reading flow by having to go search for the same page in the newer release.
 https://docs.redpanda.com/docs/21.11/data-management/data-migration/

**Comment by Deflaimun** [comment]
This will be solved by Antora. It's currently not possible with Docusaurus without a total revamp on older versions.
