### ISSUE TITLE
Update Metrics reporter

### ISSUE THREAD

**Issue by Deflaimun** [redpanda-data/documentation#1067]
### Describe the Issue

During the update for vectorizedio/redpanda it was identified that the section "enable statistics" is out of date.
It was mentioned that a new metrics reporter was introduced.  However this metrics reporter is not well documented.

There's mentions of metrics reporter at 
https://docs.redpanda.com/docs/reference/cluster-properties/
https://docs.redpanda.com/docs/reference/tunable-properties/#metrics-properties

### Updates to existing documentation

https://docs.redpanda.com/docs/manage/monitoring/
https://docs.redpanda.com/docs/reference/internal-metrics/

### New feature or content gap requests

Content Gap.

### Additional notes

https://stackbuilders.slack.com/archives/C01LK3UK2K1/p1674232332274089
Conversation at docs channel.

**Comment by Feediver1** [comment]
@shorgi Can you take a look and let us know if this is still relevant? Given all of your property and monitoring topics updates, I'm think it is obsolete. If so, can you close? If not, please assign to yourself. Thanks!

**Comment by shorgi** [comment]
"enable statistics" is being removed with the updates in #140 . 

The metrics reporter is already documented in properties `enable_metrics_reporter` at al.  I'll expand their descriptions to clarify their purpose and functionality.

**Comment by shorgi** [comment]
Being resolved in #1072
