### ISSUE TITLE
General changes to Thumbs up/Thumbs down

### ISSUE THREAD

**Issue by Feediver1** [redpanda-data/documentation#1068]
### Describe the Issue

Please implement the following updates:

1. To improve visibility, add the user feedback mechanism thumbs up/thumbs down to the right sidenav, just under the headings. So it should appear there, and in the footer.
2. The remaining footer links need to be spaced evenly and scaled properly for different devices/screen sizing. The current spacing is uneven and does not have a polished look/feel because of this.
3. Revise the text from "Was this page helpful?" to "Was this helpful?"
4. When a user clicks thumbs up, the "Solved my problem" radio button should be selected by default, and it should appear first. Move the "Easy to understand" radio button below this.
5. Revise "If we can contact you with more questions, please enter your email address:" to ""Optional: Share your email address if we can contact you about your feedback."
6. Remove the **Close** button. The only option to close the window or end the session is **Submit**.
7. Please ensure that any feedback text entered is forwarded to our documentation feedback Google group account (current tests indicate that the content is _not_ being sent to this account): https://groups.google.com/a/redpanda.com/g/rp-docs-feedback
8. In the text box (appears when user has selected "Other" radio button), revise the text "Please provide details of your feedback" to "Please share details or suggestions for this topic."

Thanks!

**Comment by Deflaimun** [comment]
Keep them in both places like google
![image](https://user-images.githubusercontent.com/5883505/214606001-34f3ae6b-e904-46c0-b9cc-20400103d84a.png)

**Comment by Feediver1** [comment]
@Deflaimun Both places, but not in the header like Google. Need it in the right sidenav, below any topic headings that are there.

**Comment by Feediver1** [comment]
@Deflaimun Feedback on the thumbs up/thumbs down in the right sidenav is that it is too close below the text, and should be moved down.  Also, the text is aligned too far left--it should be aligned with text in the navtree, not the separator line. Was this changed/moved after I approved--only ask because I think I would have seen and caught this alignment issue. Please tag me for the approval on this one. Thanks.

@danielricoh Can you please share any guidance wrt space for these types of elements?

**Comment by danielricoh** [comment]
I think you got the wrong Dan @Feediver1  maybe you meant @yougotashovel ?
