### ISSUE TITLE
Add Language label and Versions selector to mobile

### ISSUE THREAD

**Issue by shorgi** [redpanda-data/documentation#1085]
### Describe the Issue

While the search bar was added to mobile docs (#1074 ), the Desktop sidebar's Language label and Version selector have not yet been added to mobile docs.

### Updates to existing documentation

Add Language label and Version selector in mobile docs' sidebar.

**Comment by Feediver1** [comment]
@shorgi Help me understand the Language selector, as docs are not localized. If we do not offer any other language than English, what is the user going to be selecting?

**Comment by shorgi** [comment]
@Feediver1 I meant to say the Language label and version selector. Updated in issue description and title.
