### ISSUE TITLE
Explain that we now do adjacent segment merging in Tiered Storage docs

### ISSUE THREAD

**Issue by mattschumpert** [redpanda-data/documentation#1092]
### Describe the Issue

https://github.com/redpanda-data/core-internal/issues/130 changes a fairly important underlying behavior of how we manage data in customers' S3/ABS/GCS buckets. Users should be aware of this when they read up on Tiered Storage, just so they know its happening: https://docs.redpanda.com/docs/manage/tiered-storage/

A few sentences explaining it's happening and that it improves scalability and performance  are warranted.

@jcsp  is the SME here

**Comment by Lazin** [comment]
Wrote a draft for the docs. Will send it through other channel.
