### ISSUE TITLE
Add the RP Style Guide to the documentation repo landing page.

### ISSUE THREAD

**Issue by Feediver1** [redpanda-data/documentation#1097]
### Describe the Issue

Our current documentation repo landing page includes links to our RP Style Guide. However, this document is in our internal wiki. Add the Style Guide to this repo so that users submitting PRs have access to it. Update the links in the readme:
https://files.slack.com/files-pri/TPMVB7YMC-F04LPRUR1QR/image.png

**Comment by Deflaimun** [comment]
Closing it in favor of the older one https://github.com/redpanda-data/documentation/issues/721

**Comment by Deflaimun** [comment]
Reopening this one because the readme will be a bigger project
