### ISSUE TITLE
K8s: how to alter and configure kubernetes fields

### ISSUE THREAD

**Issue by coral-waters** [redpanda-data/documentation#110]
This is in the Operator but need to document how to alter kubernetes fields

This issue came up in this meeting: 
https://vectorizedio.atlassian.net/wiki/spaces/CLOUD/pages/108265483/Kubernetes+Operator

**Comment by Feediver1** [comment]
@joejulian Does any of your new material cover this? If so, we can close it. Thx.

**Comment by joejulian** [comment]
Since we're not promoting the use of the cloud operator, I think it's safe to close this. The answer to your question, however, is no. None of the new docs cover this.

**Comment by Feediver1** [comment]
Closing per @joejulian guidance. Re-open @JakeSCahill if you believe this still needs to be updated.
