### ISSUE TITLE
Customer feedback: Flags for rpk redpanda tune are not clear

### ISSUE THREAD

**Issue by Deflaimun** [redpanda-data/documentation#1135]
### Describe the Issue

From customer feedback form: 

> not clear what do this setting
> -m, --mode   string Operation Mode: one of: [sq, sq_split, mq]

The flag `-m` or `--mode` doesn't provide enough information for the user. 

### Updates to existing documentation

https://docs.redpanda.com/docs/reference/rpk/rpk-redpanda/rpk-redpanda-tune/

**Comment by shorgi** [comment]
This is being addressed by #979
