### ISSUE TITLE
Add helm chart upgrade details

### ISSUE THREAD

**Issue by vuldin** [redpanda-data/documentation#1142]
### Describe the Issue

Normally performing a `helm upgrade` to apply config changes to a deployment is simple, but some config changes will require additional steps and come with additional possible issues. For instance, if the statefulset replica count is updated and then you try to apply with `helm upgrade...` you get the following error:

```
Error: UPGRADE FAILED: cannot patch "redpanda" with kind StatefulSet: StatefulSet.apps "redpanda" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden
```

This also occurs with other parameter changes like when modifying persistent volumes.

### New feature or content gap requests

A way around this is to:
1. make the config change in values.yaml
2. delete statefulset
3. run `helm upgrade...` (which recreates an appropriately-configured statefulset)
4. perform a manual rolling restart of the pods

There is some existing documentation around this here: https://github.com/redpanda-data/helm-charts/tree/main/charts/redpanda#upgrading-chart

**Comment by JakeSCahill** [comment]
@vuldin this seems like it could be related to https://docs.redpanda.com/docs/manage/kubernetes/troubleshooting/troubleshoot/#upgrade-failed-cannot-patch-redpanda-with-kind-statefulset

if you don’t include all the previous overrides in the values flag, Helm throws this error.

@joejulian could you confirm?

**Comment by joejulian** [comment]
if you don’t include all the previous overrides in the values flag _or use --reuse-values_, Kubernetes throws this error.

**Comment by JakeSCahill** [comment]
> if you don’t include all the previous overrides in the values flag _or use --reuse-values_, Kubernetes throws this error.

Thanks, @joejulian - in that case, are we OK to close this issue since we now document this error and provide `--reuse-values` in our code snippets?
