### ISSUE TITLE
Adjust Sizing Use Cases doc based on current understanding (tiered storage, HW, etc.)

### ISSUE THREAD

**Issue by jrkinley** [redpanda-data/documentation#1164]
Product, Engineering, and Customer Success are collaborating on an updated version of this doc and we'd like to remove the current version while this is in progress: https://docs.redpanda.com/docs/deploy/deployment-option/self-hosted/manual/sizing-use-cases/.

**Comment by mattschumpert** [comment]
Making edits here: https://docs.google.com/document/d/13VWEzrlemWGfqmTHXRyJ8IBnJOJ4NpLZE9Td5YL6CwY/edit#heading=h.y8pjar85vurq

**Comment by Feediver1** [comment]
@mattschumpert I cannot access this google doc. Please add me.

**Comment by Feediver1** [comment]
@mattschumpert Is there any difference between your google doc content (which I cannot view) and the existing doc on our web site? I merged an update today, so they are out of sync. Can you please fill out this issue to indicate what, exactly, you want updated?

**Comment by micheleRP** [comment]
@jrkinley @mattschumpert: Do you have any changes yet to the sizing doc?

**Comment by mattschumpert** [comment]
@jcsp you mentioned you had a PR for this?

**Comment by micheleRP** [comment]
from Matt: The main thing was to get rid of the '1 year' retention claims for the 'long retention' case

**Comment by mattschumpert** [comment]
PR seems to be merged here: https://github.com/redpanda-data/documentation/pull/1167

**Comment by micheleRP** [comment]
@mattschumpert, @jrkinley: Can we close this issue, or is there anything else we should update immediately for the sizing use cases?

**Comment by mattschumpert** [comment]
I noticed the medium throughput case still claims a year retention, but if that's safe and @jcsp  is happy im happy.
