### ISSUE TITLE
Validate and update details in Sizing Guidelines doc

### ISSUE THREAD

**Issue by jrkinley** [redpanda-data/documentation#1165]
https://docs.redpanda.com/docs/deploy/deployment-option/self-hosted/manual/sizing/

**Comment by mattschumpert** [comment]
@travisdowns  you mentioned a couple of minor surgical updates to this one.  Can you recommend in comments?

**Comment by mattschumpert** [comment]
FYI @Feediver1

**Comment by Feediver1** [comment]
@mattschumpert @travisdowns If this is a P1, we need specific guidance ASAP. Please put that guidance here so that @micheleRP can make the required updates. Thx.

**Comment by Feediver1** [comment]
The docs still include several instances of "infinite retention"--is there going to be a global update? Does each require a different value based on context? Please advise.

We already merged  #1167  from @jcsp - should we use those updates in all the remaining contexts?

**Comment by micheleRP** [comment]
Closing this as fixed by https://github.com/redpanda-data/documentation/pull/1178 and https://github.com/redpanda-data/documentation/pull/1252. Please reopen if anything is currently missing!
