### ISSUE TITLE
Document segment.ms support

### ISSUE THREAD

**Issue by Feediver1** [redpanda-data/documentation#1189]
### Describe the Issue

Add `segment.ms` topic configuration property. If a segment is older than this, it rolls even if its size is below the size limit for segments.

See https://github.com/redpanda-data/core-internal/issues/270

In Kafka, this property helps people who have a time based retention setting, but a low data rate: they roll segments so that their retention policy can take effect, as retention rules only apply to sealed segments.

@shorgi I'm not sure if we need to doc, as this appears to be a Kafka property that we are saying we are compatible with/we simply support. Can you vet with @andijcr?

Eng PR: https://github.com/redpanda-data/redpanda/pull/8047

**Comment by shorgi** [comment]
Increased estimate from 2 to 5 because documenting segment.ms requires adding a new topic properties reference and documenting the other currently undocumented topics properties.
