### ISSUE TITLE
Fix name of Kafka Rust client

### ISSUE THREAD

**Issue by shorgi** [redpanda-data/documentation#1255]
### Describe the Issue

In https://docs.redpanda.com/docs/develop/kafka-clients/#kafka-client-compatibility, the name of the client for Rust should be`kafka-rust`.

### Updates to existing documentation

Fix https://docs.redpanda.com/docs/develop/kafka-clients/#kafka-client-compatibility, the name of the client for Rust should be`kafka-rust`.

**Comment by Feediver1** [comment]
Fixed in `dev` and `versioned_docs/version-22-3`.
