### ISSUE TITLE
new folder structure for shared content

### ISSUE THREAD

**Issue by micheleRP** [redpanda-data/documentation#1278]
### Describe the Issue

The new single-sourcing folder structure (seen in [this PR](https://github.com/redpanda-data/documentation/pull/1198) puts items that all topics anywhere could use, like the enterprise license admonition, in docs/shared. For content in docs/manage, shared items go in docs/manage/shared. In future, if reference topics have content to share, we'll create new folder for docs/reference/shared. 

This issue suggest that all shared content be put in the same folder structure; e.g., docs/shared/manage (instead of docs/manage/shared). Like this:

docs/shared
      _manage
      _deploy
      _develop
      _reference

I think this makes it easier to visually manage and find all shared content.

### Updates to existing documentation

yes

**Comment by Feediver1** [comment]
I like that this simplifies the construction of the shared data links @micheleRP 

Let's discuss at our next team mtg. 
^^ @JakeSCahill

**Comment by Feediver1** [comment]
@micheleRP It appears that this was fixed by #1276 
Closing as a duplicate. If I'm misunderstanding, then please re-open.

**Comment by micheleRP** [comment]
@Feediver1: This wasn't really fixed as a dup of #1276, but I think this issue can be tabled until the Antora migration. 
@JakeSCahill: Do we need an issue like this for the migration? I still think it'd be cleaner & clearer to have shared content set up as described in this issue, instead of how we currently have it.
