### ISSUE TITLE
Dark mode text and background displaying incorrectly

### ISSUE THREAD

**Issue by Feediver1** [redpanda-data/documentation#1311]
### Describe the Issue

Both internal and external users have reported that dark mode is preventing them from seeing text:

![image (10)](https://user-images.githubusercontent.com/102751339/222274180-fb43d6f1-7b58-4d70-9b86-c589d3236768.png)

Please investigate whether or not recent updates to font color are the culprit. Thx.

**Comment by shorgi** [comment]
@Deflaimun - revert setting the body color to black: https://github.com/redpanda-data/documentation/pull/1237/files#diff-44813f307e729042af7e70beff6f32ea63a7941bc100043a49e84d229ea2570fR487-R490

**Comment by JakeSCahill** [comment]
Fixed in https://github.com/redpanda-data/documentation/pull/1313
