### ISSUE TITLE
Standardize terminology (object storage)

### ISSUE THREAD

**Issue by JakeSCahill** [redpanda-data/documentation#1317]
### Describe the Issue

Suggestion from @jcsp

> Style point: shall we standardize on saying "object storage" instead of "cloud storage"/"the cloud"/"remote storage"?
It's a bit more technically correct and will help the content make sense in the future when we support self-hosted customers using tiered storage with their own on-prem object stores.

### Updates to existing documentation

Docs that use synonyms for object storage such as "cloud storage"/"the cloud"/"remote storage".

We should also update our style guide to clarify the right term to use.

**Comment by shorgi** [comment]
Includes updating 'cloud storage' label in this image: https://docs.redpanda.com/assets/images/tiered_storage-53070c8ba4fd8190a45cb81b56e4b0ef.png
