### ISSUE TITLE
Create banner for EOL versions

### ISSUE THREAD

**Issue by Deflaimun** [redpanda-data/documentation#1356]
### Describe the Issue

Create new banner for EOL versions. 

[This document](https://vectorizedio.atlassian.net/wiki/spaces/CORE/pages/16711857/Releases+Backports) goes into detail about our versioning scheme.

**Comment by Deflaimun** [comment]
@micheleRP What should be the text on the banner? 

This is our current one 
![image](https://user-images.githubusercontent.com/5883505/224120321-7813ed61-1107-41bb-b4cc-fa144ce90186.png)

And we have PR https://github.com/redpanda-data/documentation/pull/1351 to change it to 

> This is the documentation for Redpanda v22.3.
For up-to-date documentation, see the [latest version](https://deploy-preview-1351--redpanda-documentation.netlify.app/docs/home/) (23.1).

**Comment by micheleRP** [comment]
My vote is for that suggested text : 
This is the documentation for Redpanda v22.3.
For up-to-date documentation, see the [latest version](https://deploy-preview-1351--redpanda-documentation.netlify.app/docs/home/) (23.1).

This would also get updated similarly for 22.2, right?

**Comment by micheleRP** [comment]
Sorry, for banners on EOL versions (21.11 and 22.1), I suggest: 
This is the documentation for Redpanda v21.11, which is no longer supported.
For up-to-date documentation, see the [latest version](https://deploy-preview-1351--redpanda-documentation.netlify.app/docs/home/) (23.1).

**Comment by JakeSCahill** [comment]
Implemented here: https://github.com/JakeSCahill/redpanda-docs-ui/commit/6e69fc1a1aa786dff303027ef85ea8bc97ded559
