### ISSUE TITLE
Broker and Admin API Addresses

### ISSUE THREAD

**Issue by AnneLeeperRP** [redpanda-data/documentation#1371]
This topic explains when to use `--brokers` on the command line and when to use `--api-urls`, and why these addresses are needed (so rpk can communicate with the Redpanda cluster). This distinction has confused a lot of users in the Redpanda Community Slack channel. The explanation will include a table to summarize which commands use which flag.

NOTE: The `rpk redpanda admin` commands use `--hosts` instead of `--api-urls`, which introduces inconsistency and confusion. This needs to be fixed by Eng (https://github.com/redpanda-data/redpanda/issues/9433)

The topic will include a sample `rpk` section from a `redpanda.yaml` file, showing the `kafka_api` section with the `brokers` declaration, and the `admin_api` section with the `addresses` declaration.

The topic will explain three different methods for setting `--brokers` and `--api-urls`, and the order of precedence (which setting overrides which):
* On the command line
* As an environment variable (if no command line flag is used)
* In the `redpanda.yaml` file (if no env. var. is specified)

SME: @r-vasquez

**Comment by r-vasquez** [comment]
Linked the https://github.com/redpanda-data/redpanda/issues/9433 issue in the original issue description @AnneLeeperRP
