### ISSUE TITLE
Reusable content

### ISSUE THREAD

**Issue by h-garcia** [redpanda-data/documentation#139]
We want the flexibility of having reusable page-independent text along with associated media

Some usage examples:
* Disclaimers
* Footnotes
* Common content 
* Time-sensitive content

**Acceptance Criteria**
* Investigate a way of having reusable components that would include text and other media 
* Create an internal guide on how to use these reusable components

**Comment by Feediver1** [comment]
Ticket is stale and most issues addressed in latest UI and content updates.
