### ISSUE TITLE
rpk: generate grafana-dashboards improvements and Grafana Labs

### ISSUE THREAD

**Issue by r-vasquez** [redpanda-data/documentation#1394]
### Describe the Issue

Currently, our docs (https://docs.redpanda.com/docs/reference/internal-metrics/#configure-grafana-internal-metrics) point to generating the Grafana Dashboard using the command `rpk generate grafana-dashboard`, however, we are now uploading a set of improved dashboards to Grafana Labs in https://grafana.com/grafana/dashboards/?search=redpanda

We have a set of issues to change the way things work in rpk:
- https://github.com/redpanda-data/redpanda/issues/6502
- https://github.com/redpanda-data/redpanda/issues/9485

The goal of this ticket is to:

1. Change the documentation to point to the Grafana labs page.
2. Document the new features in rpk once the two tickets listed above are implemented.

SME: @r-vasquez

**Comment by micheleRP** [comment]
Hi @shorgi. I marked this as P2 new feature, but I don't think it's on our doc roadmap yet. It might be an epic with multiple doc issues.

**Comment by Feediver1** [comment]
Looks like this is an enhancement provided to eng by the CS team.

**Comment by r-vasquez** [comment]
PR: https://github.com/redpanda-data/documentation/pull/1525
