### ISSUE TITLE
Improve search quality in looking up config properties

### ISSUE THREAD

**Issue by daisukebe** [redpanda-data/documentation#1405]
### Describe the Issue

When I search for `segment.ms`, which is a topic property, the top of the current search results is for `log_segment_ms`, which is a corresponding cluster property but not what I'm looking for.

![image](https://user-images.githubusercontent.com/350206/226231071-687908d2-2e1a-4c72-9e1c-dab881685e9a.png)

What I really should be able to find is this specific section https://docs.redpanda.com/docs/manage/cluster-maintenance/disk-utilization/#log-rolling though, I have to scroll down a bit further. Until then some less relevant search results come up.

Finally I've found a relevant page but it points out to a different section in the same page, https://docs.redpanda.com/docs/manage/cluster-maintenance/disk-utilization/#segment-size-for-compacted-segments, `log-rolling` vs `segment-size-for-compacted-segments`

![image](https://user-images.githubusercontent.com/350206/226231399-d28e9909-74b4-4a9d-938f-2b5b657f2b3c.png)

I could imagine two improvements here

* Show up the most relevant page & section in the top result, https://docs.redpanda.com/docs/manage/cluster-maintenance/disk-utilization/#log-rolling
* Include some relevant text snippets that matches the search keyword in the search result. In this case, something like this `segment.ms is a topic-level property that configures the default segment rolling timeout`.

**Comment by shorgi** [comment]
The in-progress PR for a new topic-level properties reference page (#958) will add a `segment.ms` heading that should become the top search result. 

Nevertheless, our search result ranking and sorting can be improved. Currently, heading text that contains the search terms is always ranked higher than body text that contains the search terms.

**Comment by Deflaimun** [comment]
This has been solved by Antora. Currently we auto generate the data in Docusaurus using the built-in crawler. Antora is using a custom crawler to setup its index pages.
