### ISSUE TITLE
single source NodeJS example and do similar cleanup for Go and Python examples

### ISSUE THREAD

**Issue by micheleRP** [redpanda-data/documentation#1411]
### Describe the Issue

The Node JS sample is duplicated 3 times in our doc set:
- https://docs.redpanda.com/docs/develop/guide-nodejs/
- https://docs.redpanda.com/docs/get-started/code-examples/
- https://docs.redpanda.com/docs/develop/code-examples/

The version that now is correct with PR #1402 is https://docs.redpanda.com/docs/develop/guide-nodejs/. 

Suggest putting the single source for this correct content into https://docs.redpanda.com/docs/get-started/code-examples/ and removing the other 2 pages with redirects. (Note that the 23.2 roadmap has an item for building a new advanced sample application.)

The Go and Python examples on https://docs.redpanda.com/docs/get-started/code-examples/ need to be tested and updated similar to way the NodeJS example was updated, so content can be easily copy/pasted. 

### Updates to existing documentation

- https://docs.redpanda.com/docs/develop/guide-nodejs/
- https://docs.redpanda.com/docs/get-started/code-examples/
- https://docs.redpanda.com/docs/develop/code-examples/

**Comment by Feediver1** [comment]
@shorgi I just discovered this ticket, which appears to have been updated/added while I was out on PTO. @micheleRP shared that you helped out while docs on call, and created an updated nodeJS example (thanks for jumping in and helping out--great teamwork!).

Just today, I assigned the Day 1 (build a sample app/Kafka client libraries) and 2 (build a "real world" production app) client example content to @JakeSCahill. Moving forward, Jake will own these topics. Can you work together to hand off what you completed so far? Thanks!
