### ISSUE TITLE
Remote Read Replica clusters must be upgraded first

### ISSUE THREAD

**Issue by JakeSCahill** [redpanda-data/documentation#1443]
### Describe the Issue

We need to document the fact that Remote Read Replica clusters must be upgraded before the source cluster.

### Updates to existing documentation

- https://docs.redpanda.com/docs/manage/cluster-maintenance/rolling-upgrade/
- https://docs.redpanda.com/docs/manage/kubernetes/rolling-upgrade/
- https://docs.redpanda.com/docs/manage/remote-read-replicas/
- https://docs.redpanda.com/docs/manage/kubernetes/remote-read-replicas/

**Comment by Feediver1** [comment]
This was fixed in Issue1261

**Comment by Feediver1** [comment]
Duplicate
