### ISSUE TITLE
Need a more specific IAM role name used in EKS deployment guide

### ISSUE THREAD

**Issue by supahcraig** [redpanda-data/documentation#1446]
### Describe the Issue

Following the EKS install guide can potentially cause problems during the helm install step if the IAM role created by the `eksctl create iamserviceaccount` step already exists.   That step will report back with an error about the role already existing, but most users would believe that they could proceed safely with that particular error.

However the role that is created in that step has a trust policy tied to the OIDC provider for the EKS cluster.   If that role already exists (as it does in the Redpanda AWS sandbox-support acct), it will have a trust policy tied to some prior EKS cluster which will cause the helm install to fail with a cryptic timeout error. 

### Updates to existing documentation

https://docs.redpanda.com/docs/deploy/deployment-option/self-hosted/kubernetes/eks-guide/

The simplest solution is to modify the name of the role to be more user/cluster-specific.   Typically this would be in the form of a command line substitution or an environment variable, but the so-called "in line replacement" would also work and doesn't introduce any os-specific syntax.

From Step 2 in the guide:

```
eksctl create iamserviceaccount \
    `# Do not change the name. It is required by EKS.` \
    --name ebs-csi-controller-sa \
    `# Do not change the namespace. It is required by EKS.` \
    --namespace kube-system \
    --cluster redpanda \
    --attach-policy-arn arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy \
    --approve \
    --role-only \
    --role-name AmazonEKS_EBS_CSI_DriverRole-<cluster-name>
```

And then in step 3 a corresponding change must be made to account for the new role name.

```
eksctl create addon \
    --name aws-ebs-csi-driver \
    --cluster redpanda \
    --service-account-role-arn arn:aws:iam::${AWS_ACCOUNT_ID}:role/AmazonEKS_EBS_CSI_DriverRole-<cluster-name> \
    --force
```

_It does seem worth noting that an environment variable for the cluster name could be leveraged in several other places in this guide and would ultimately be easier for the end user, although it would make for a more complicated change to the docs, and would probably prompt similar changes to the GKE & EKS guides._

**Comment by JakeSCahill** [comment]
I think the editable placeholders is a good idea here. To make this more user-friendly, we should improve the editable placeholders feature so that matching placeholders are all changed at once.

I was thinking we could cache previously used values in local storage, but for things like SASL user passwords, this wouldn't be a good idea.
