### ISSUE TITLE
Use consistent terminology for `server.key` vs `node.key`

### ISSUE THREAD

**Issue by shorgi** [redpanda-data/documentation#1463]
### Describe the Issue

From community Slack https://redpandacommunity.slack.com/archives/C01AJDUT88N/p1680532193968609, we need to fix and use consistent terminology for `server.key` and `node.key`:

> I have been following redpanda docs to configure encryption in my redpanda server.
I have a doubt in this step - https://docs.redpanda.com/docs/manage/security/encryption/#configure-tls. In this step, the docs is telling me to update redpanda.yaml with server.key and server.crt locations. Is this server.key and server.crt same as node.key and node.crt which we created in earlier steps?

### Updates to existing documentation

References to `server.key` and `node.key`

**Comment by shorgi** [comment]
@micheleRP - this is a follow up to PR #1148: we need to use the existing `server.key` terminology or update them to `node.key`

**Comment by micheleRP** [comment]
SME = Travis Campbell
