### ISSUE TITLE
EKS deployment guide - bad command & example outputs

### ISSUE THREAD

**Issue by supahcraig** [redpanda-data/documentation#1464]
### Describe the Issue

**Issue 1:** kubectl command for verifying that Redpanda is scheduled on each node is incorrect.  Somewhere along the way a label changed and this command didn't get updated accordingly.

**Issue 2:**  very minor, but the corresponding expected output section isn't fully representative of what the output actually looks like.

**Issue 3:**  the output from `rpk-topic describe` is not exactly what is returned (based on the instructions in the guide).   This is also minor, but the guide appears to show that some other config options have been set that aren't super relevant to the guide itself.

### Updates to existing documentation
https://docs.redpanda.com/docs/deploy/deployment-option/self-hosted/kubernetes/eks-guide/?operating-system=macos

**Issue 1:  wrong label in the filtering section of the kubectl command under Deploy Redpanda and redpanda console**

https://docs.redpanda.com/docs/deploy/deployment-option/self-hosted/kubernetes/eks-guide/?operating-system=macos#deploy-redpanda-and-redpanda-console

the label used in filter of the given command is `app.kubernetes.io/component=redpanda` but this doesn't return anything because there is no matching label when you do a `kubectl describe pod`.   I believe this should be `app.kubernetes.io/component=redpanda-statefulset` which returns output similar to what is in the Expected Output section.

```
kubectl get pod -n redpanda  \
-o=custom-columns=NODE:.spec.nodeName,NAME:.metadata.name -l \
app.kubernetes.io/component=redpanda-statefulset,job-name!=redpanda-redpanda-configuration,job-name!=redpanda-post-upgrade
```

---

**Issue 2:  Expected Output isn't perfect**

The expected output from the command in Issue 1 above is missing the header row, and the node field could look a little more representative than just "example-worker-0".   This is what the actual output looks like.  Obviously the IP's & AWS region will be unique to each deployment, and I am open to ideas on how to best represent that variability in the documentation.   Although given that it is _example_ output, it's probably ok to leave the domain names exactly as they appear here.

```
NODE                                           NAME
ip-192-168-59-212.us-east-2.compute.internal   redpanda-0
ip-192-168-75-108.us-east-2.compute.internal   redpanda-1
ip-192-168-25-198.us-east-2.compute.internal   redpanda-2
```

---

Issue #3:  rpk-topic describe output isn't 100% correct

This is pretty minor, but as long as we're touching the docs we may as well have this be 100% correct.   If you follow the guide to the letter, the output will look as follows.  The way it currently is looks like somebody made some cluster config changes that aren't accounted for in the guide, and aren't necessary to complete the guide successfully.

```
SUMMARY
=======
NAME        twitch_chat
PARTITIONS  1
REPLICAS    1

CONFIGS
=======
KEY                           VALUE       SOURCE
cleanup.policy                delete      DYNAMIC_TOPIC_CONFIG
compression.type              producer    DEFAULT_CONFIG
max.message.bytes             1048576     DEFAULT_CONFIG
message.timestamp.type        CreateTime  DEFAULT_CONFIG
redpanda.remote.delete        true        DEFAULT_CONFIG
redpanda.remote.read          false       DEFAULT_CONFIG
redpanda.remote.write         false       DEFAULT_CONFIG
retention.bytes               -1          DEFAULT_CONFIG
retention.local.target.bytes  -1          DEFAULT_CONFIG
retention.local.target.ms     86400000    DEFAULT_CONFIG
retention.ms                  604800000   DEFAULT_CONFIG
segment.bytes                 134217728   DEFAULT_CONFIG
segment.ms                    1209600000  DEFAULT_CONFIG
```

**Comment by JakeSCahill** [comment]
Issue 1 was fixed in #1374 

For issue 2, we reuse (single-source) these example outputs for all our guides. It reduces the maintenance burden. If it's OK with you, I'd rather leave this one as is. As you say, the exact addresses will differ from user to user anyway.
