### ISSUE TITLE
Doc config setting for node quotas

### ISSUE THREAD

**Issue by Feediver1** [redpanda-data/documentation#1495]
[Slack thread](https://redpandadata.slack.com/archives/C01ND4SVB6Z/p1681139445999459)

What are the name of the configs for node quota settings?
https://docs.redpanda.com/docs/reference/cluster-properties/
includes the following quota config options:
```
kafka_connection_rate_limit
kafka_connection_rate_limit_overrides
kafka_connections_max
kafka_connections_max_overrides
kafka_connections_max_per_ip
kafka_throughput_limit_node_in_bps
kafka_throughput_limit_node_out_bps
```
^^ are some configs without the word “quota” - these are useful to configure back-pressure (the only way to config back pressure)

Soln: write up content that describes how to best set the throughput limits until we handle back pressure gracefully.

**Comment by shorgi** [comment]
I already wrote relevant content in PR #1140 and published as [Node-wide throughput limits](https://docs.redpanda.com/docs/manage/cluster-maintenance/manage-throughput/#node-wide-throughput-limits).

To improve the docs to address this issue: 
- Add cross reference links in the properties reference page to the topic
- Add "back-pressure" keyword to topic and/or properties
