### ISSUE TITLE
Document Topic-aware leadership balancer configurations

### ISSUE THREAD

**Issue by daisukebe** [redpanda-data/documentation#1520]
### Describe the Issue

v23.1.7 ships a new feature, [Topic-aware leadership balancer](https://github.com/redpanda-data/redpanda/pull/7997), which carries two possible configuration options; `random_hill_climbing` (default) and `greedy_balanced_shards`

We should document what they are and when we should change it from the default.

### Updates to existing documentation

Maybe here? https://docs.redpanda.com/docs/manage/cluster-maintenance/cluster-balancing/#partition-leadership-balancing

### New feature or content gap requests

@ballard26 , can you help to document the properties?

### If new feature, in which release is it included or expected? 

v23.1.7

### Additional notes

https://redpandadata.slack.com/archives/C03H26FHJQL/p1681890899234889

**Comment by Feediver1** [comment]
@micheleRP and @shorgi Looks like this hits both partition leadership balancing (guidance) and properties (new properties) pages.

**Comment by micheleRP** [comment]
From @mattschumpert: Include the following 23.2 updated covered [here](https://docs.google.com/document/d/1_iNFSdMJtbX_iXVdeQJz8ZRzdQ9DcYpDay3CAm5zj4w/edit): 
- Topic-aware leadership balancing (spread topic workload evenly)
- Improved data balancing (smarter, safer and more consistent partition moves)
