### ISSUE TITLE
Add Java code samples in topics under Develop

### ISSUE THREAD

**Issue by Feediver1** [redpanda-data/documentation#1523]
My understanding is that this is a PM ask. Looks like this is for the building an app/client libraries context.

Docs to add java code examples to appropriate topics under:
https://docs.redpanda.com/docs/develop/

cc: @mattschumpert  @StasiaZam

**Comment by mattschumpert** [comment]
Yes please!!  Java likely has the largest market share in Kafka client usage (CS estimates 40%)

**Comment by StasiaZam** [comment]
@Feediver1 - maybe this will help to accelerate the work: https://github.com/redpanda-data-university/rp-101-redpanda-getting-started/tree/main/03-basic-streaming/java-tutorial-maven. It's from our academy.
