### ISSUE TITLE
Create BYOC in AWS has bad cloudv2.redpanda.com link

### ISSUE THREAD

**Issue by supahcraig** [redpanda-data/documentation#1526]
### Describe the Issue

The very first step in the guide has "redpanda" misspelled in the `cloudv2.redpanda.com` link where we instruct the users to go there to login.

### Updates to existing documentation

https://docs.redpanda.com/docs/deploy/deployment-option/cloud/create-byoc-cluster-aws/

<img width="974" alt="image" src="https://user-images.githubusercontent.com/34287157/233225948-609c2dd3-eac1-40e7-8327-b29b67540964.png">

the URL is incorrectly spelled `cloudv2.repanda.com` but should be `cloudv2.redpanda.com`

Note "redpanda" is misspelled. 

It might not be a terrible idea to actually make that a link that opens in a new tab.

**Comment by Feediver1** [comment]
These are now fixed.
