### ISSUE TITLE
Document Automatic Disk Space Management (23.2)

### ISSUE THREAD

**Issue by mattschumpert** [redpanda-data/documentation#1560]
https://github.com/redpanda-data/core-internal/issues/303

Auto-purging of local disk under disk pressure and treatment of TS cache and local topic storage as a single managed bucket of storage are both critical improvements to Tiered Storage to be added to our TS docs page.  

Config properties around the size of TS cache are likely to change to percentages vs fixed size in GB (subject to final implementation).  This implies updating our config reference pages as well

**Comment by Feediver1** [comment]
1 of 6 issues in engineering epic are complete as of June 8th--no guidance for docs yet.
