### ISSUE TITLE
Document Tiered Storage Fine-Grained Caching (23.2)

### ISSUE THREAD

**Issue by mattschumpert** [redpanda-data/documentation#1561]
https://github.com/redpanda-data/core-internal/issues/374

A major change to how Tiered Storage caches data on local disk that needs documenting in our Tiered Storage docs. Docs currently explain how we download entire segments from object storage to disk when promoting to cache(which will change), and this will significantly change performance/scale characteristics of Tiered Storage reads and how one might want to configure the cache size / think about disk space needs for cache

**Comment by Feediver1** [comment]
SME=[Abhijat Malviya](https://github.com/abhijat)
