### ISSUE TITLE
Block indexing of outdated docs pages in Google and other web crawlers with noindex rule

### ISSUE THREAD

**Issue by shorgi** [redpanda-data/documentation#1567]
### Describe the Issue

To preclude Google and other web crawlers from returning search results of outdated pages (for example, see Slack thread https://redpandadata.slack.com/archives/C01LK3UK2K1/p1683141199955129), one recommended mechanism is to add a noindex rule on a page-by-page basis:

`<meta name="robots" content="noindex">` or `<meta name="googlebot" content="noindex">`

For reference, see https://developers.google.com/search/docs/crawling-indexing/block-indexing

### Updates to existing documentation

For each outdated page we don't want indexed, tag with `<meta ... content="noindex">`

**Comment by Feediver1** [comment]
@shorgi Does this issue still exist? Please work with @Deflaimun to determine if this work should still move forward. Thx.
