### ISSUE TITLE
Update Ansible docs

### ISSUE THREAD

**Issue by micheleRP** [redpanda-data/documentation#1574]
### Describe the Issue

Update doc to reduce complexity and improve customer experience when deploying with Ansible.

Ansible slides: https://docs.google.com/presentation/d/15jxLfTTDdVObWVC8pCg4-7W1cvJP4B5_4aBQnoiDcqs/edit#slide=id.p
Ansible demo: https://drive.google.com/file/d/1BRUgr4LIx1rVJ8qsR3RYZXmdBefuAq66/view
Readme: https://github.com/redpanda-data/deployment-automation
Docs for the Terraform module: https://registry.terraform.io/modules/redpanda-data/redpanda-cluster/aws/latest & Ansible collection: https://galaxy.ansible.com/redpanda/cluster

SME: Gene Lang, Denis Coady

### Updates to existing documentation

https://docs.redpanda.com/docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation/

### New feature or content gap requests

Enhanced doc (content gap)

**Comment by gene-redpanda** [comment]
Content generated by terraform and ansible now gets dumped into the artifacts directory rather than directly into the repo's content root:

```
root@efda4e28ea75:/app# ls -ltrah artifacts/
total 56K
-rw-r--r-- 1 root root  159 Apr 11 16:18 README.md
-rw-r--r-- 1 root root   51 Apr 11 16:18 .gitignore
-rw-r--r-- 1 root root  743 May  4 20:12 testkey.pub
-rwx------ 1 root root 3.4K May  4 20:12 testkey
-rwxr-xr-x 1 root root  567 May  4 20:14 hosts_aws_devex-cicd.ini
drwxr-xr-x 1 root root 4.0K May  4 20:14 ..
drwxr-xr-x 6 root root 4.0K May  4 20:14 roles
drwxr-xr-x 3 root root 4.0K May  4 20:14 collections
drwxr-xr-x 2 root root 4.0K May  4 20:14 logs
drwxr-xr-x 2 root root 4.0K May  4 20:20 tmp
drwxr-xr-x 1 root root 4.0K May  4 20:20 .
drwxr-xr-x 2 root root 4.0K May  4 20:20 bin
```

This includes any downloaded roles or collections.
