### ISSUE TITLE
Update organization references from `vectorized` to `redpandadata` in container image names

### ISSUE THREAD

**Issue by ivotron** [redpanda-data/documentation#1604]
### Describe the Issue

The legacy `vectorized` dockerhub org is still referenced in some places. All references to docker images should be to the new org:

```
docker.redpanda.com/redpandadata/[image]
```

where `[image]` is any of the images that we distribute (`redpanda`, `connectors`, `console`, etc.)

### Updates to existing documentation

These two searches show results:
  * https://github.com/search?q=repo%3Aredpanda-data%2Fredpanda%20vectorized%2Fredpanda&type=code
  * https://github.com/search?q=repo%3Aredpanda-data%2Fdocumentation%20vectorized%2Fredpanda&type=code

### If the requested update is from customer feedback or a Community slack conversation, provide a link:

cc: @emaxerrno

**Comment by Feediver1** [comment]
Hi @ivotron 
This is a duplicate of https://github.com/redpanda-data/documentation/issues/644
@Deflaimun has been working to remedy this for quite some time now, but is also dependent on dev fro some of these.
Paulo--please provide a status update.

If okay with you Ivo, I will close this new ticket and let Paulo proceed with the existing one.

**Comment by ivotron** [comment]
> If okay with you Ivo, I will close this new ticket and let Paulo proceed with the existing one.

yes, that works. thanks @Feediver1!
