### ISSUE TITLE
Add missing properties

### ISSUE THREAD

**Issue by shorgi** [redpanda-data/documentation#1620]
### Describe the Issue

From https://redpandadata.slack.com/archives/C01LK3UK2K1/p1684582070125979:

- ~~This one seems present in the code but not in the docs:
storage_ignore_timestamps_in_future_sec
https://github.com/redpanda-data/redpanda/blob/v23.1.10/src/v/config/configuration.cc#L909~~ added by #1524 

- kafka_enable_partition_reassignment

- ~~compaction_ctrl_p_coeff~~ already documented, https://docs.redpanda.com/docs/reference/tunable-properties/#compaction_ctrl_p_coeff 
- [cloud_storage_roles_operation_timeout_ms](https://github.com/redpanda-data/redpanda/blob/v23.1.10/src/v/config/configuration.cc#L1225)
- [cloud_storage_graceful_transfer_timeout](https://github.com/redpanda-data/redpanda/blob/v23.1.10/src/v/config/configuration.cc#L1383), although it seems like there is a typo in the code?
- [cloud_storage_backend](https://github.com/redpanda-data/redpanda/blob/v23.1.10/src/v/config/configuration.cc#L1391)
- [cloud_storage_credentials_host](https://github.com/redpanda-data/redpanda/blob/90c6b20932ae8bd4c49e973d48e634c470356e6d/src/v/config/configuration.cc#LL1405C5-L1405C35)

From https://redpandadata.slack.com/archives/C01LK3UK2K1/p1684816434583889:
- https://docs.redpanda.com/docs/reference/tunable-properties/#cloud_storage_housekeeping_interval_ms seems to be missing a link to https://docs.redpanda.com/docs/manage/tiered-storage/#object-storage-housekeeping

From https://redpandadata.slack.com/archives/C01LK3UK2K1/p1684819895271489:
- ~~It seems like https://github.com/redpanda-data/redpanda/blob/dev/src/v/config/configuration.cc#L1529 is best defined as per its PR description instead:~~ the property corresponding to the PR description below isn't `cloud_storage_cache_size`
```
Maximum number of segments per CPU core that may be promoted into a readable state from cloud storage. 
This may be tuned downward to reduce memory consumption at the possible cost of read throughput
```

**Comment by c4milo** [comment]
Update on the one with the typo: https://github.com/redpanda-data/redpanda/pull/10947

**Comment by c4milo** [comment]
* [leader_balancer_mode](https://github.com/redpanda-data/redpanda/blob/v23.1.10/src/v/config/configuration.cc#L1650)
* [memory_abort_on_alloc_failure](https://github.com/redpanda-data/redpanda/blob/v23.1.10/src/v/config/configuration.cc#L1743)

**Comment by shorgi** [comment]
https://github.com/redpanda-data/documentation/pull/1524 added storage_ignore_timestamps_in_future_sec

**Comment by c4milo** [comment]
@shorgi, I should have used a permalink the description of `cloud_storage_max_materialized_segments_per_shard`: 
https://github.com/redpanda-data/redpanda/blob/bc7bacdbe84c430c6c198ecfe87ff2ba65938e98/src/v/config/configuration.cc#L1549
```
Maximum number of segments per CPU core that may be promoted into a readable state from cloud storage. 
This may be tuned downward to reduce memory consumption at the possible cost of read throughput
```
