### ISSUE TITLE
doc edit UI strings

### ISSUE THREAD

**Issue by micheleRP** [redpanda-data/documentation#1662]
### Describe the Issue

Edit [UI strings](https://github.com/redpanda-data/cloudv2/blob/dev/apps/cloud-ui/src/i18n/lang/en.json ) according to [UI text style guidelines](https://vectorizedio.atlassian.net/wiki/spaces/DOC/pages/377683969/UI+Text+Style+Guide).

SME = Beniamin Malinski

### Updates to existing documentation

https://github.com/redpanda-data/cloudv2/blob/dev/apps/cloud-ui/src/i18n/lang/en.json

**Comment by Deflaimun** [comment]
Linked
https://github.com/redpanda-data/cloudv2/pull/6381

**Comment by micheleRP** [comment]
> 
Actually that's a different one. This one is linked with https://github.com/redpanda-data/cloudv2/pull/6578
