### ISSUE TITLE
Document compat issue between Redpanda using ABS and storage accounts configured for hierarchical namespaces

### ISSUE THREAD

**Issue by VladLazar** [redpanda-data/documentation#1712]
### Describe the Issue

Redpanda configured for Azure Blob Storage is incompatible with storage accounts configured for [hierarchical namespaces](https://learn.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-namespace) (and implicitly [ADSLv2](https://learn.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-introduction)).

Redpanda uses the `2021-08-06` Blob Storage REST API version and  this compat issue is not documented by microsoft (should be [here](https://learn.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-known-issues)).

### Updates to existing documentation

We should add a callout similar to:

> Currently, Redpanda requires a dedicated container, and that container should be in a storage account configured in a way that's compatible with Redpanda: this includes not enabling hierarchical namespace support.

### Additional notes
https://redpandadata.slack.com/archives/C02BDN76HUK/p1687281815037389

**Comment by Deflaimun** [comment]
How about:

> Redpanda doesn't support containers that have hierarchical namespace enabled.

**Comment by VladLazar** [comment]
I don't really mind what the wording is, but the dedicated container bit is also relevant (i.e. the storage account should only contain one container for Redpanda's use).
