### ISSUE TITLE
Guide on Puppet automation for Redpanda

### ISSUE THREAD

**Issue by JakeSCahill** [redpanda-data/documentation#1714]
### Describe the Issue

We have a page that explains how to automate Redpanda deployments with Terraform/Ansible. But, we do not provide any docs for automating deployments with Puppet. Puppet is another popular DevOps tool for deployment automation.

The Ansible docs rely on scripts available at https://github.com/redpanda-data/deployment-automation. We should consider whether we want to support Puppet in the same way, which would involve examples and documentation.

### Updates to existing documentation

https://docs.redpanda.com/docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation/

**Comment by Feediver1** [comment]
Given PM feedback, closing as will not fix. If/when eng & PM decide to implement, docs will too.
