### ISSUE TITLE
K8s Operator uses a different repo

### ISSUE THREAD

**Issue by JFlath** [redpanda-data/documentation#1728]
### Describe the Issue

We actually maintain two Helm repos:

`https://charts.vectorized.io/` for the Operator and `https://charts.redpanda.com/` for Redpanda and Console.

These can co-exist (but may merge in the future), but if using both, you need to set a different name for them. Our docs for the Operator suggest calling it `redpanda` which clashes with the other docs where we *also* suggest that name:

https://docs.redpanda.com/docs/reference/redpanda-operator/kubernetes-qs-cloud/

```
helm repo add redpanda https://charts.vectorized.io/ && \
helm repo update
```

https://docs.redpanda.com/docs/deploy/deployment-option/self-hosted/kubernetes/local-guide/ (Note, this is the case for all sub-pages, e.g. AKS)

```
helm repo add redpanda https://charts.redpanda.com
...
```

### Updates to existing documentation

We should use a new name (probably actually an _old_ name - `vectorized`?) for the Operator chart to avoid the clash. We should also probably point out explicitly that it's a different repo above the command, as it's very easy to skim over and say "Yup, already installed the redpanda repo" without realising.

**Comment by Feediver1** [comment]
FYI - @emaxerrno has requested that all instances of "vectorized" be removed from docs. That will not be an option for the new name.

**Comment by JakeSCahill** [comment]
Part of #644
