### ISSUE TITLE
Remove Labs entry from doc navtree in 23.1

### ISSUE THREAD

**Issue by Feediver1** [redpanda-data/documentation#1736]
### Issue description

As is in 23.1, the [Labs entry](https://docs.redpanda.com/docs/labs/) in the navtree provides a bad user experience: it says no Labs are available in the release, so there is no information of value on this page. If that is the case, then there is no reason to have this heading/entry in the navtree for 23.1. We can add it back in again if/when we have a new Labs feature.

### Updates to existing documentation

Remove the Labs entry from 23.1

**Comment by Deflaimun** [comment]
Should we delete the page or just remove the entry from the navtree ?

**Comment by Feediver1** [comment]
> Should we delete the page or just remove the entry from the navtree ?

I suspect we will eventually have a labs feature again, so makes sense to keep the page but remove from the navtree. Thx
