### ISSUE TITLE
Document known issue wrt scaling groups and impact on nodes

### ISSUE THREAD

**Issue by Feediver1** [redpanda-data/documentation#1776]
### Issue description

https://redpandadata.slack.com/archives/C01LK3UK2K1/p1689787948526979

Follow this conversation ^^

### Updates to existing documentation

https://docs.redpanda.com/docs/manage/tiered-storage/

### Link to Redpanda Slack conversation

https://redpandadata.slack.com/archives/C01LK3UK2K1/p1689787948526979

**Comment by micheleRP** [comment]
This was added to the PR for the 23.2 GA release: https://github.com/redpanda-data/documentation/pull/1778: 

TIP
: If deploying Redpanda on an AWS Auto-Scaling group (ASG), keep in mind that the ASG controller terminates nodes and spins up replacements if the nodes saturate and are unable to heartbeat the controller (based on the EC2 health check). For more information, see the [AWS documentation](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/monitoring-system-instance-status-check.html#types-of-instance-status-checks). Redpanda recommends deploying on Linux or Kubernetes. For more information, see [Deploy Redpanda](https://deploy-preview-1778--redpanda-documentation.netlify.app/docs/deploy/deployment-option/self-hosted/).
