### ISSUE TITLE
Improve event tracking through Algolia

### ISSUE THREAD

**Issue by Deflaimun** [redpanda-data/documentation#1792]
### Issue description

In order for us to capture more info from Algolia we must send them custom events, so that we can know more about Searches without results and searches without clicks.

Reference: 
https://www.algolia.com/doc/guides/search-analytics/overview/
https://www.algolia.com/doc/guides/building-search-ui/events/js/
https://www.algolia.com/doc/api-reference/api-methods/send-events/

**Comment by Feediver1** [comment]
Made it a P2 because it is blocking an OKR

**Comment by JakeSCahill** [comment]
> we must send them custom events, so that we can know more about Searches without results and searches without clicks

I've configured the Antora site to send viewed and clicked events. So we can see the ratio of users who searched and clicked/didn't click. Is this enough?

![2023-07-25_21-28-43](https://github.com/redpanda-data/documentation/assets/45230295/c1466c12-a5e8-4f4d-8c17-26c7392f54ed)

**Comment by Deflaimun** [comment]
I think so. I'm going to close this issue, and check again once we migrate.
