### ISSUE TITLE
rpk iotune is not in the 23.2 release

### ISSUE THREAD

**Issue by weimeilin79** [redpanda-data/documentation#1799]
### Issue description

I don't see `rpk iotune` available in the 23.2 release, should we remove it from the doc? 

### Updates to existing documentation

https://docs.redpanda.com/docs/reference/rpk/rpk-iotune/

**Comment by Feediver1** [comment]
@r-vasquez Can you tell me if this command is deprecated? Or should it be in 23.2?

**Comment by r-vasquez** [comment]
For me it's there:

![image](https://github.com/redpanda-data/documentation/assets/59714880/3d7f6ed6-822b-4804-ae97-e8f8ae8682de)


@weimeilin79  Which OS are you using? This command is only available in Linux and won't appear in rpk for Macs/Windows.

**Comment by twmb** [comment]
iotune is only visible on Linux -- this has always been the case, too, so we haven't changed anything with the 23.2 release here

**Comment by weimeilin79** [comment]
I see, make sense, I was using my mac, (maybe a word in there would be good)
and how about below? I assume they are only available to Linux too correct?  @twmb 

```
- rpk redpanda check
- rpk redpanda config
- rpk redpanda mode
- rpk redpanda start
- rpk redpanda stop
```

**Comment by weimeilin79** [comment]
Cool, I started a linux container and tested all the above. Sorry about that.
