### ISSUE TITLE
Broker / Producer / Consumer configuration

### ISSUE THREAD

**Issue by coral-waters** [redpanda-data/documentation#181]
Possibly three separate pages with configuration details for each. This will include keys settings and how they affect behavior. 

Slack thread where this came up: https://redpandadata.slack.com/archives/C01LK3UK2K1/p1644829914167969

Confluent's page: https://docs.confluent.io/platform/current/installation/configuration/producer-configs.html#producerconfigs_acks

Info from Dais and James: 
![image](https://user-images.githubusercontent.com/95656677/153871486-bfcb69c9-7b19-4156-800f-169d2ffa80d9.png)
![image](https://user-images.githubusercontent.com/95656677/153871538-92408f64-146c-4576-8ccd-f0cb5ee13ed2.png)

**Comment by Feediver1** [comment]
Producer is DONE: https://docs.redpanda.com/docs/develop/produce-data/configure-producers/
Consumer is in flight and has another ticket, so track here: https://github.com/redpanda-data/documentation/issues/1100

Closing this ticket in lieu of 
https://github.com/redpanda-data/documentation/issues/1100
