### ISSUE TITLE
redpanda_cluster_brokers using incorrect description of metric

### ISSUE THREAD

**Issue by hcoyote** [redpanda-data/documentation#1816]
### Issue description

https://docs.redpanda.com/docs/reference/public-metrics-reference/#redpanda_cluster_brokers

Current doc states redpanda_cluster_brokers is "Number of nodes up in a cluster." and will adjust up or down according to the state of running brokers. This appears to be different than what the metric HELP says and the behavior seen in a test cluster.

The metric states it is 
```
# HELP redpanda_cluster_brokers Number of configured brokers in the cluster
# TYPE redpanda_cluster_brokers gauge
```

I dug back through the doc history and it looks like this was the description in docs around 22.2 and changed in 22.3.

The behavior is confirmed to be a steady state of configured brokers that are fully commissioned, whether they are up or not.

From my test on a five node cluster. I killed one node. I only saw the metric change when the cluster membership changed.

```
redpanda@61d12f48a048:/$ rpk cluster health
CLUSTER HEALTH OVERVIEW
=======================
Healthy:               false
Controller ID:               0
All nodes:                   [3 4 1 0 2]
Nodes down:                  [2]
Leaderless partitions:       []
Under-replicated partitions: [kafka_internal/id_allocator/0 redpanda/controller/0]

redpanda@61d12f48a048:/$ curl -s localhost:9644/public_metrics | grep redpanda_cluster_brokers
# HELP redpanda_cluster_brokers Number of configured brokers in the cluster
# TYPE redpanda_cluster_brokers gauge
redpanda_cluster_brokers{} 5.000000


```

and then forced a decommission

```
redpanda@61d12f48a048:/$ rpk redpanda admin brokers decommission 2 --force
Success, broker 2 has been decommissioned!

redpanda@61d12f48a048:/$ curl -s localhost:9644/public_metrics | grep redpanda_cluster_brokers
# HELP redpanda_cluster_brokers Number of configured brokers in the cluster
# TYPE redpanda_cluster_brokers gauge
redpanda_cluster_brokers{} 4.000000

```

### Updates to existing documentation

https://docs.redpanda.com/docs/reference/public-metrics-reference/#redpanda_cluster_brokers

and probably each of the version copies. 

I confirmed the above behavior with 23.1.13.

### Link to Redpanda Slack conversation

https://redpandadata.slack.com/archives/C02J9EWK39S/p1690840000601029 

note: this is a private slack channel, if docs team wants to see full history let me know so I can invite you. But gist of conversation is above:

**Comment by hcoyote** [comment]
Probably worth confirming with @VladLazar what the intended metric behavior is, but pretty sure it's just configured, not up and running.

https://github.com/redpanda-data/redpanda/blame/3e84194806913e6251bcf00f003ae35ac93fb669/src/v/cluster/controller_probe.cc#L69-L77

**Comment by VladLazar** [comment]
Thanks for reporting this Travis. Your assessment is correct; the metric tracks the configured number of brokers.
