### ISSUE TITLE
Minor updates to "What's New"

### ISSUE THREAD

**Issue by Feediver1** [redpanda-data/documentation#1836]
### Issue description

1. Please revise the first note that appears from "Redpanda Cloud releases new features on a continuous basis and includes the latest Redpanda platform major version."
to:
"Redpanda Cloud releases new features on a continuous basis and always includes the content from the latest version of Redpanda platform."

2. Please revise "finer-grained caching" to "fine-grained caching"--this will be consistent with the announcement and other RP collateral. 

### Updates to existing documentation

https://docs.redpanda.com/docs/get-started/whats-new/

### Link to Redpanda Slack conversation

Ran by @mattschumpert already

**Comment by Feediver1** [comment]
@micheleRP If no response, I think we can remove the note--it contradicts guidance I heard during the retrospective. 

If any issues @mattschumpert please chime in now. Thx.

**Comment by mattschumpert** [comment]
Up to you how to structure this @Feediver1 , I think you have the raw info on what's in/out now
