### ISSUE TITLE
Host our own CRD reference page

### ISSUE THREAD

**Issue by Deflaimun** [redpanda-data/documentation#211]
Currently the reference CRD operator for Kubernetes page is hosted by another party at 
https://doc.crds.dev/github.com/vectorizedio/redpanda

We need to find a way to host it ourselves.

**Comment by Feediver1** [comment]
How/where the CRD reference page is hosted is outside the scope of the docs team @Deflaimun 
Also, we don't really recommend Operator - want customers using Helm chart.
