### ISSUE TITLE
add next steps to kubernetes quickstarts 

### ISSUE THREAD

**Issue by coral-waters** [redpanda-data/documentation#222]
Note: this is blocked until we have something like a "build your first real-time app" documentation page. 

Issue: 
I created three new kubernetes quickstarts: 

- [Kubernetes quickstart for cloud](https://docs.redpanda.com/docs/getting-started/kubernetes-qs-cloud)
- [Kubernetes quickstart with local access](https://docs.redpanda.com/docs/getting-started/kubernetes-qs-local-access)
- [Kubernetes quickstart with minikube](https://docs.redpanda.com/docs/getting-started/kubernetes-qs-minikube) 

The quickstarts all end with a "clean up" step that should be changed to "next steps" when when we have something else for them to do with the cluster that they created in the quickstart. Then the last step will give them the option of cleaning up or going on to the next thing. 

I asked vivek where the quickstart could point them and this is what he said: 

> I suspect the next thing would be a “build your first real-time app” (actually I added that as one of the items on the tentative redpanda docs organization). This would probably be fine as an independent page which all the quickstarts would link to (unless we find there are platform-specific elements for building the app)

**Comment by Feediver1** [comment]
Note: Relates to Operator, so lower priority.

**Comment by JakeSCahill** [comment]
Status: We aren't working on issues for Operator at the moment. This issue will be fixed when the new Redpanda Operator is released.
