### ISSUE TITLE
Create API Portal

### ISSUE THREAD

**Issue by Deflaimun** [redpanda-data/documentation#224]
We need to create an API Portal to be the reference page for all of Redpandas's REST API specs.
During our study, we came into the conclusion that we should use [Swagger-UI](https://swagger.io/tools/swagger-ui/)

Pros: 
- Open source
- Free
- Easy to use

How:
On Swagger's installation notes, they mention a Docker Engine with a nginx server on it
https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/installation.md#docker

From our understanding, we should have this pointed at the Redpanda repo to generate a website that looks similar to this:
https://app.swaggerhub.com/apis/BenPope/pandaproxy-rest/0.0.2

(note that swagger-hub, their cloud service, doesn't seem to be an option since it's paid)

**Comment by JakeSCahill** [comment]
Could we use this Docusaurus plugin? I've tried it before and it works pretty well. https://github.com/PaloAltoNetworks/docusaurus-openapi-docs

**Comment by shorgi** [comment]
Closing, as we've since created [API references](https://docs.redpanda.com/docs/reference/api-reference/) for Admin API, Schema Registry, and HTTP proxy.
