### ISSUE TITLE
Customer Feedback: Document Prometheus annotations in CRD

### ISSUE THREAD

**Issue by h-garcia** [redpanda-data/documentation#27]
**AC**

- add a note to get started that Prometheus annotations are set by the operator automatically.
- Add section in Deployment for monitoring the deployment
- Document the annotations
- Link to the Prometheus metrics or link to GitHub
- Document other ways to monitor K8s (pod monitor, monitor operator itself)

https://vectorized.atlassian.net/browse/VD-6

**Comment by Feediver1** [comment]
Docs never got the information requested/needed to work on this ticket. Closing. If this is something PM or eng wants in docs, or if a customer has requested, let's re-open and get it in, but docs would still need more clear and specific guidance than is in this ticket.
