### ISSUE TITLE
docker quickstart updates

### ISSUE THREAD

**Issue by coral-waters** [redpanda-data/documentation#288]
These should at least go in the [docker quickstart](https://docs.redpanda.com/docs/quickstart/quick-start-docker), but also wherever else we document using docker - 

1. Redpanda issue [ksql server failed to start #3874](https://github.com/redpanda-data/redpanda/issues/3874) - To make this work with ksqldb you have to specify the cluster id. I asked about this in the docs slack channel. See responses here - https://redpandadata.slack.com/archives/C01LK3UK2K1/p1648297396066619
2. Martin S. noted that you should not have to manually edit the redpanda version in the docker compose file. If this can be done with a variable, we can use the steps from the [kubernetes quickstart guides](https://docs.redpanda.com/docs/quickstart/kubernetes-qs-local-access#step-4-use-helm-to-install-the-redpanda-operator). If not, maybe we can set it to latest? ([slack conversation](https://redpandadata.slack.com/archives/C01LK3UK2K1/p1648292327623979))

**Comment by JakeSCahill** [comment]
The original issue was based on documenting a bug that's been fixed: https://github.com/redpanda-data/redpanda/pull/4457

**Comment by JakeSCahill** [comment]
The issue about versions is being tracked here: https://github.com/redpanda-data/documentation/issues/1035
