### ISSUE TITLE
Showing configs/rpk commands for tech preview features as being in tech preview

### ISSUE THREAD

**Issue by vsaraswat** [redpanda-data/documentation#306]
### Who is this for and what problem do they have today?

Some of our Redpanda features are in tech preview as of today -- Wasm, Transactions, Idempotency. 

In the config parameters section of the docs (https://docs.redpanda.com/docs/cluster-administration/configuration/#optional-parameters), we should explicitly label any parameters related to these features as technical preview. Especially any "enable" commands.

Also in the rpk page (https://docs.redpanda.com/docs/reference/rpk-commands/) any high level commands for a tech preview feature should be labeled as such, e.g. `rpk wasm`. 

### What would you like fixed in or added to the documentation?

For config page:
`enable_transactions` 
`coproc` parameters
`transactional` parameters

(Note if we reorganize the parameters page by subject area, this becomes a lot easier to label tech preview stuff in one place)

For rpk page:
`rpk wasm`

### Is this a new feature or a gap in the documentation?

Gap

**Comment by shorgi** [comment]
Closing this issue, as we have no features currently in labs (tech preview). When such features are introduced, should add a  badge for labs/preview features.
