### ISSUE TITLE
Missing description for cluster properties

### ISSUE THREAD

**Issue by marcopsb** [redpanda-data/documentation#317]
During the centralized configuration documentation writing some properties were missing description in the code.
Following are the properties that are missing information:
- compaction_ctrl_update_interval_ms
- cloud_storage_upload_ctrl_update_interval_ms

**Comment by Feediver1** [comment]
Data is now there:
https://docs.redpanda.com/docs/reference/tunable-properties/#compaction_ctrl_update_interval_ms
https://docs.redpanda.com/docs/reference/tunable-properties/#cloud_storage_upload_ctrl_update_interval_ms
