### ISSUE TITLE
Change github issue to form format

### ISSUE THREAD

**Issue by Deflaimun** [redpanda-data/documentation#319]
Our current issues on github today are on text format. 

This is an old way to do this. The new and improved way is to present a form to the user.

This link explains how to achieve it.
https://beyondco.de/blog/github-issue-forms

**Comment by Feediver1** [comment]
Also see: https://github.com/facebook/docusaurus/issues/new?assignees=&labels=documentation%2Cstatus%3A+needs+triage&template=documentation.yml
