### ISSUE TITLE
differences from kafka semantics

### ISSUE THREAD

**Issue by coral-waters** [redpanda-data/documentation#321]
As @patrickangeles said - "we probably need a docs page that has a summary of differences from Kafka semantics (for those times when we haven’t yet fixed it in the code)"

slack conversation - https://redpandadata.slack.com/archives/C01ND4SVB6Z/p1649298190349879

**Comment by Feediver1** [comment]
As I read the original Sack thread, PM/CS/eng was to add the relevant updates. 

@jcsp @mattschumpert

**Comment by jcsp** [comment]
I don't have anything top of mind for this -- if there aren't specific questions, we should probably just close this.
