### ISSUE TITLE
Separate CLI install from service instantiation

### ISSUE THREAD

**Issue by vuldin** [redpanda-data/documentation#343]
### Who is this for and what problem do they have today?
I just had to go through the new laptop setup last week, and I noticed something about the quick start guide that was different than what I initially expected.

The section is here: https://docs.redpanda.com/docs/quickstart/quick-start-linux/#install-and-run-redpanda

This section combines both installing the CLI and running redpanda as a service on the system. But really all I was expecting was to install the CLI, and then be able to use for starting up a cluster later. Maybe this page isn't the right one to be looking at for this, but it seems to be the right one based on the title and location in the sidebar table of contents.

Another thing about defaulting to starting the service at install time is that I expect this cluster ends up not being used by some people. Instead, they likely forget or don't know about this cluster and then use the CLI to start up subsequent clusters.
What do you think about either 1) separating the CLI installation from the service enablement steps on this page, or 2) having another "Getting started" or "Quick start" page focused on just installing the CLI?

I looked around a little and found that the mac instructions already do exactly what I was expecting, which is provide instructions for just installing the CLI: https://docs.redpanda.com/docs/quickstart/quick-start-macos/

Also the beta install page is almost exactly what would be needed for the the linux quickstart page (maybe they should be the same page?): https://docs.redpanda.com/docs/deployment/install-preview/

As a new user looking to install `rpk`, I'm looking for a command or two that does this and expect to see it in the quickstart section.
Instead, the instructions found in multiple pages provide steps for installing the CLI and starting up a service.
The user may or may not already have some ideas on the type of cluster they want to spin up with `rpk`. They may want to use Kind, minikube, some other kubernetes... they may already have a Redpanda cluster in a container.
But after following the current instructions they will now have the `rpk` CLI along with a brand new instance provided by the service regardless of what they wanted to use `rpk` for.

### What would you like fixed in or added to the documentation?
These two tasks (CLI install and service instantiation) should be split into separate steps, and the quickstart guides could be simplified to just focus on installing the CLI.
There are other guides/instructions that show how to start a cluster with `rpk`, and so I'm not sure the initial quickstart guide would need to go into those details (instead it could just point them to those docs). But if so then it would just be `rpk container start`.

Personally, I don't know when I would ever want to install a Redpanda service. It is so easy to run `rpk container start`, and on top of that I can easily configure the cluster with arguments to that command (changing node size, etc.). But if keeping the service as an option during install is useful for others than maybe it could be listed as an optional step after installing the CLI (and used in place of `rpk container start`).

### Is this a new feature or a gap in the documentation?
This is a gap, which is that there is no documentation focused solely on installing the CLI.

### Link to existing product documentation page and/or community slack conversation, if applicable
Existing slack discussion:
https://redpandadata.slack.com/archives/C01LK3UK2K1/p1651529346963949

Doc pages that would need to be updated:
https://docs.redpanda.com/docs/quickstart/quick-start-linux/
https://redpanda.com/platform/

### Additional notes

@Feediver1

**Comment by Feediver1** [comment]
@vuldin As you know, we recently updated the docs and also created a new RP Quickstart to handle all installs via Docker. Production installs are handled now in https://docs.redpanda.com/docs/deploy/deployment-option/self-hosted/manual/production/production-deployment/
We also now have a separate rpk install here: https://docs.redpanda.com/docs/get-started/rpk-install/
Hoping these updates satisfy your request. Please let me know if you are good with these updates wrt this ticket and I can close. Thx!

**Comment by vuldin** [comment]
Absolutely @Feediver1 , thanks for circling back on this. We now give details on how to install rpk separately from redpanda so I think this issue can be closed.
