### ISSUE TITLE
Customer Reported: K8s Operator config doc examples throw errors for user

### ISSUE THREAD

**Issue by Feediver1** [redpanda-data/documentation#353]
### Who is this for and what problem do they have today?

See https://redpandacommunity.slack.com/archives/C01AJDUT88N/p1651708055395559

New RP user encountered errors when using an example from the https://docs.redpanda.com/docs/deployment/kubernetes-connectivity/#:~:text=The%20Redpanda%20operator%20ensures%20that,an%20external%20port%20for%20RPC
doc.

using the one_node_cluster  example, I get the following error.
```
kubectl apply \
-n panda-chat \
-f https://raw.githubusercontent.com/redpanda-data/redpanda/dev/src/go/k8s/config/samples/one_node_cluster.yaml
error: error validating "https://raw.githubusercontent.com/redpanda-data/redpanda/dev/src/go/k8s/config/samples/one_node_cluster.yaml": error validating data: [ValidationError(Cluster.spec.configuration): unknown field "adminApi" in io.vectorized.redpanda.v1alpha1.Cluster.spec.configuration, ValidationError(Cluster.spec.configuration.kafkaApi): invalid type for io.vectorized.redpanda.v1alpha1.Cluster.spec.configuration.kafkaApi: got "array", expected "map", ValidationError(Cluster.spec.configuration): unknown field "pandaproxyApi" in io.vectorized.redpanda.v1alpha1.Cluster.spec.configuration, ValidationError(Cluster.spec.configuration): unknown field "schemaRegistry" in io.vectorized.redpanda.v1alpha1.Cluster.spec.configuration]; if you choose to ignore these errors, turn validation off with --validate=false
```

When using the `--validate=false`  flag, he got another error:
`The Cluster "one-node-cluster" is invalid: spec.configuration.kafkaApi: Invalid value: "array": spec.configuration.kafkaApi in body must be of type object: "array"`

### What would you like fixed in or added to the documentation?

Contact the K8s Operator SME to figure out what update is required. Circle back with customer in community slack channel after this is resolved. (User is Bhavesh Pandey; post was in Community Slack on May 4 @6:15 pm CST)

**Comment by JakeSCahill** [comment]
I tested the doc and it's working. As this issue is quite old, I expect that the issue was fixed in the code.
