### ISSUE TITLE
Add an RPK Redpanda quick start guide based on blog posts

### ISSUE THREAD

**Issue by h-garcia** [redpanda-data/documentation#36]
Docs should be the source of truth whereas blog posts are more to introduce certain features. 

**AC**

- Review blog posts like the one below to create a quick start guide for RPK Redpanda — https://vectorized.io/blog/getting-started-rpk/#Introducing-code-classlanguage-textrpk-apicode

**Comment by Feediver1** [comment]
See #886  
I think all of the old Quickstarts/current install docs need attention--the content and focus for each platform is different. Some have you install rpk, others don't. Some include guidance on producing and consuming, or creating a one-node or 3-node cluster, while others don't. Closing this ticket and opening a new ticket to address all of the Quickstart inconsistencies.
