### ISSUE TITLE
Explain that upgrades are finalized only when the last broker is upgraded

### ISSUE THREAD

**Issue by mattschumpert** [redpanda-data/documentation#362]
1. During cluster upgrade, the logical cluster version is incremented only when the last active broker is upgraded, marking the 'point of no return' with upgrades, as downgrades are not supported.  If problems occur with specific brokers that are active, the upgrade is not committed.

1. Additionally, beginning with 22.1, new feature enablement is intentionally suppressed until all brokers are upgraded to prevent unexpected behavior relating to new features.

Both of these facts are important for operators but are missing from : https://docs.redpanda.com/docs/cluster-administration/version-upgrade/

**Comment by Feediver1** [comment]
This will be handled in https://github.com/redpanda-data/documentation/issues/1010
