### ISSUE TITLE
Add some important caveats in the Upgrade Guide

### ISSUE THREAD

**Issue by daisukebe** [redpanda-data/documentation#415]
### Who is this for and what problem do they have today?

Current `Version upgrade` guide doesn't mention about the following important caveats, specifically for upgrade from 21.11 to 22.1:

* Group topic migration
* Downgrade capability

### What would you like fixed in or added to the documentation?

We should be very clear that:

* As soon as all nodes are up and running with 22.1, it starts to migrate the consumer group topics to `__consumer_offsets`, which is a new feature introduced in 22.1 for Kafka compatibility. It will take some time depending on the data size, and until it finishes all consumer group related operations (consume, offset commit, coordinator election, etc) will be blocked.

* Once the cluster is upgraded to 22.1, there's no supported way to downgrade to the previous major version, 21.x.y. 

### Is this a new feature or a gap in the documentation?

Gap

### Link to existing product documentation page and/or community slack conversation, if applicable

https://docs.redpanda.com/docs/cluster-administration/version-upgrade/

### Additional notes

We've learned this from the latest incident with Jump Trading, at #inc-2022-05-21-jumptrading-data-read-stopped-after-221. Will post more details soon.

**Comment by Feediver1** [comment]
This should go into https://github.com/redpanda-data/documentation/issues/1010

Closing this as a duplicate, but adding the request to https://github.com/redpanda-data/documentation/issues/1010.
