### ISSUE TITLE
Note about data directory corruption in troubleshooting guide

### ISSUE THREAD

**Issue by mattschumpert** [redpanda-data/documentation#422]
We need to make it clear in https://docs.redpanda.com/docs/support/#troubleshooting that a partially corrupted or user-modified data directory of a broker can lead to inconsistent states that may be unrecoverable.

Our suggestion here should be as follows:

1. files in the data directory should never be directly manipulated by administrators
2. If any files are missing/corrupted/deleted from the data directory of a broker and you want to attempt to partially recover this data, please put this node into maintenance mode, stop Redpanda on this node, and then contact Redpanda support.  
3. Alternatively, if you are OK losing all the data on this node (including any partitions hosted on the node which may or may not be replicated), you can remove the _entire_ data directory and restart, which will cause Redpanda to recover the node

**Comment by Deflaimun** [comment]
Page no longer exists, so it doesn't apply anymore.
