### ISSUE TITLE
Core: Admin API Docs + Swagger

### ISSUE THREAD

**Issue by vsaraswat** [redpanda-data/documentation#434]
### Who is this for and what problem do they have today?

Our Admin API (used for managing/configuring brokers, creating/deleting/updating topics, etc.) is currently undocumented. 

### What would you like fixed in or added to the documentation?

Our eng team is planning on creating Swagger (API reference) for Admin API. We should implement this within our docs Reference section.

### Is this a new feature or a gap in the documentation?

Gap

### Additional notes

Relevant Eng Leads: @BenPope

**Comment by Feediver1** [comment]
@piyushredpanda @mattschumpert 
There was a request for this material [in Redpanda Community Slack](https://redpandacommunity.slack.com/archives/C01AJDUT88N/p1667229466627559) yesterday. @emaxerrno shared that it should be going out next quarter (4Q2022). Is this being included in our next release? Please advise.

**Comment by Feediver1** [comment]
See also: https://github.com/redpanda-data/redpanda/issues/3149

**Comment by Feediver1** [comment]
Here is the latest guidance from PM:

We need to do this badly.  There's a tradeoff between generating the skeleton from swagger without explaination of each API call and eng time to explain it.  I would argue we should just get the skeleton out there (have docs work with eng to auto-generate it), and do manual doc (explanation) of the individual API calls over time.

Once this automation is setup I'd argue it's something docs can do with each release (suck up the swagger definition from our redpanda repo and publish it).  Separately we should develop a practice of adding the right doc to each API method in dev.

Start by working with I suggest working with @dotnwat 

Target for 23.2 or earlier. Much-requested doc.

**Comment by Feediver1** [comment]
@shorgi After 23.1 GAs, please make this a top priority ticket. Request from PM:

This sounds like a great candidate for doing in between releases (developing the automation once 23.1 ships if we have the cycles).  It would be great if we had this content for for 22.3 and 23.1 for example (people need it for existing releases).... even if eng isn't able to write exactly what each API does, at least they'd know what APIs they can call and its often quite self explanatory.

E.g. from Cloudera, this was auto-generated via swagger: https://archive.cloudera.com/cm7/7.2.4/generic/jar/cm_api/apidocs/index.html. method descriptions could be filled in as we go.

^^ @mattschumpert As long as the writer can get what he needs from eng in a timely manner, we can prioritize.
