### ISSUE TITLE
Custom configuration page: custom config file path

### ISSUE THREAD

**Issue by h-garcia** [redpanda-data/documentation#48]
Custom configuration page (https://vectorized.io/docs/configuration) contains info where Redpanda expects a config file by default (/etc/redpanda/redpanda.yaml), but no mentions how to provide a custom path. 
afair it’s by adding: --config /home/user/rpk.yaml param

Slack: https://stackbuilders.slack.com/archives/C02EXBXERKP/p1638275227300400

**Acceptance Criteria**
- Add a config file custom path reference to the Custom configuration page 
- Review and add additional details on each parameter. e.g. https://stackbuilders.slack.com/archives/C02EXBXERKP/p1647272599251929

**Comment by Feediver1** [comment]
Custom config has been gone for a couple of releases/versions now, and is no longer recommended.
