### ISSUE TITLE
bug: problems with the mobile version

### ISSUE THREAD

**Issue by Deflaimun** [redpanda-data/documentation#480]
Currently our mobile version has several bugs. 

1. The search function doesn't show up sometimes. 
![image](https://user-images.githubusercontent.com/5883505/177446397-cd0af898-7ecd-42a6-91ca-4cc359b4a638.png)

2. The switch to night mode overlaps the new logo
![image](https://user-images.githubusercontent.com/5883505/177446613-6a450c55-e795-48f0-8a25-7e04b872ade7.png)

3. The button above "Back to main menu" doesn't make sense to us. Should be either removed or renamed. It takes us to the same links that we have in our header with no option to get back the the regular sidebar.
![image](https://user-images.githubusercontent.com/5883505/177447855-d0f27734-6481-401b-b65e-e495279f8a9b.png)

4. It's impossible to change versions

5. Some tables don't render properly based on the view-port/media
![image](https://user-images.githubusercontent.com/5883505/177446977-2029fc54-a056-4a04-8ae5-7a132fa2ff3b.png)
https://docs.redpanda.com/docs/introduction/intro-to-events/

**Comment by Feediver1** [comment]
@shorgi added the Search function (https://github.com/redpanda-data/documentation/issues/1074), but the rest of these items need to be addressed.
