### ISSUE TITLE
Create a separate "Cloud" section in the documentation 

### ISSUE THREAD

**Issue by sameers361** [redpanda-data/documentation#485]
### Who is this for and what problem do they have today?
Cloud customers have no central place to go to inside Redpanda documentation to read through the relevant information for FMC and BYOC deployments

### What would you like fixed in or added to the documentation?

Add a new section in the docs for Cloud as outlined in 
https://docs.google.com/document/d/1XvQR30OYyoTY8n8BPKYoA9nmkd1mYFhOjhSI8OcIJaE/edit#heading=h.5utzv0tntc9c

### Is this a new feature or a gap in the documentation?

Gap

#### If new feature, what's the expected release number and date? 

Q3 FY 2022

**Comment by Feediver1** [comment]
We delivered the first iteration of Redpanda Cloud docs on Nov 1, 2022. Closing this ticket.
