### ISSUE TITLE
Community channel: Update configuration doc to identify the assigned IP address before runtime

### ISSUE THREAD

**Issue by Feediver1** [redpanda-data/documentation#529]
### Describe the Issue

See https://redpandacommunity.slack.com/archives/C01AJDUT88N/p1658777960682529

Customer was able to connect to a Docker image using:
`rpk topic list --brokers="127.0.0.1:9092"`
However, he was unable to connect when he ran:
```
rpk topic list --brokers="redpanda-1.internal:9092"
unable to request metadata: unable to dial: dial tcp [fdaa:0:4939:a7b:ab2:1:4e05:2]:9092: connect: connection refused
```

### Updates to existing documentation

https://docs.redpanda.com/docs/cluster-administration/configuration/
Update the appropriate configuration topic to address how to connect your broker before runtime.
Update needs to:
- Clarify which IP address is assigned to users before runtime.
- Provide explanations of all the startup options and what they are used for.

### If the requested update is from customer feedback or a Community slack conversation, provide a link:
https://redpandacommunity.slack.com/archives/C01AJDUT88N/p1658777960682529

**Comment by shorgi** [comment]
Closing, already fixed in docs/get-started/broker-admin/ by #1399
