### ISSUE TITLE
Add automation tests to test documentation code snippets

### ISSUE THREAD

**Issue by andrewhsu** [redpanda-data/documentation#537]
Each docs page Getting Started guide runs through CLI steps that can be automated to make sure they don't break

Shortcut requester: @benmansheim
Shortcut url: https://app.shortcut.com/vectorized/story/2739

**Comment by Feediver1** [comment]
This seems more like a tools automation update than a doc request. I'm reassigning to tools @ivotron . If not within your scope, please close, as it is not within the scope of the doc team.

**Comment by Feediver1** [comment]
This seems more like a tools automation update than a doc request. I'm closing this ticket because  it is not within the scope of the doc team. If still requested, I think this should be filed against tools automation. Thoughts @ivotron
