### ISSUE TITLE
Implement Hubot to ensure Slack conversations with doc requests get turned into doc Issues

### ISSUE THREAD

**Issue by Feediver1** [redpanda-data/documentation#550]
### Describe the Issue

Quite often there are internal Slack discussions that result in doc update requests. These conversations occur in a variety of channels that the doc mgr and team never see. So we sometimes miss important updates that will help improve the customer experience. This ticket request will (hopefully) address this gap.
### Updates to existing documentation

Request is to implement hubot to turn Slack conversations into Doc Issues.

See:  https://github.com/mbland/hubot-slack-github-issues

### New feature or content gap requests

This is not a doc feature. Rather, it is a process improvement to ensure important doc updates that come from Slack conversations are captured in a doc Issue.

**Comment by Feediver1** [comment]
@tdewitt With SOC2, will this be possible/allowed? Please advise. Thx

**Comment by ivotron** [comment]
Tucker just found out today that the official github app is now capable of this: https://github.blog/changelog/2022-10-19-github-app-in-slack-issue-create-and-manage-experience/ would that be enough to cover the needs of your team, @Feediver1 ?

**Comment by Feediver1** [comment]
Closing, as people can now use a git integration to do this:
We have integrated GitHub with the Slack [#help-docs](https://redpandadata.slack.com/archives/C01LK3UK2K1) channel. Moving forward, you can create a new doc issue from within a Slack conversation here, which makes it quicker and easier to transfer the conversation directy into a new doc issue.
To create a new doc issue in a channel: `/github open redpanda-data/documentation`
or
click the three dots in the conversation and select  "Create an Issue"
