### ISSUE TITLE
Document supported / tested upgrade scenario

### ISSUE THREAD

**Issue by daisukebe** [redpanda-data/documentation#552]
### Describe the Issue

Most of customers are running v21.11.x right now. We've released v22.1 and will release v22.2 soon, but we don't have a clear guideline on what's the supported upgrade path from v21.11.x to v22.2. 

### Updates to existing documentation

https://docs.redpanda.com/docs/cluster-administration/version-upgrade/ is missing the information

### New feature or content gap requests

The core engineering team is testing the upgrade scenario over https://github.com/redpanda-data/redpanda/issues/5920, therefore the doc should align with the result and give a proper guideline to the readers.

### Additional notes

Slack
#release-22_2_1 https://redpandadata.slack.com/archives/C03PGC3DWVD/p1660023232134759
#core https://redpandadata.slack.com/archives/C01ND4SVB6Z/p1660021226351389

**Comment by mattschumpert** [comment]
@Feediver1 @micheleRP critically, we only test moving a single version when upgrading but customers could easily attempt 'skip version' upgrades.

We should document that users should always only upgrade 1 'major' Redpanda version at a time (e.g. 22.1 to 22.2 and then 22.3)

Can we make this change to all upgrade pages ASAP , or at least before 22.3

cc @jcsp

**Comment by Feediver1** [comment]
@Deflaimun 
Please include the updates requested by @mattschumpert above in the PR for this issue. Thanks!

**Comment by Deflaimun** [comment]
It's not clear to me what's the proposed change. Also, @Feediver1 I don't have access to the channels

**Comment by Feediver1** [comment]
@Deflaimun The PR should be sufficient: https://github.com/redpanda-data/redpanda/issues/5920
If not, please contact @mattschumpert for additional guidance.

**Comment by Feediver1** [comment]
@Deflaimun 
I don't think we have a policy until we have proper testing, but I refer you to my previous comment: https://redpandadata.slack.com/archives/C01ND4SVB6Z/p1660005122543629?thread_ts=1660002450.814019&cid=C01ND4SVB6Z
The actual general form is to:
go to xx.yy.latest
go to xx.yy+1.latest (rollover xx if appropriate, and reset yy to 1)
goto 2
