### ISSUE TITLE
3Q 22.3 Feature: HELM Chart v2 Documentation

### ISSUE THREAD

**Issue by vladoschreiner** [redpanda-data/documentation#592]
### Describe the Issue

There is a new version of the HELM Chart released in Aug 2022 https://github.com/redpanda-data/helm-charts/
It's not covered in the docs, so it's invisible to Redpanda users.
The context is gonna be useful for users running Redpanda on Kubernetes.

### Updates to existing documentation

Add Helm chart to the Quickstart for Kubernetes. 
Provide the kind, minikube or the cloud way.
Use the readme of the Helm as a source of information: https://github.com/redpanda-data/helm-charts/

Update the Deployment > Kubernetes accordingly.

Refer to the github repository with [readme](https://github.com/redpanda-data/helm-charts) and [examples](https://github.com/redpanda-data/helm-charts/tree/main/examples) to enable specific setups.

### If the requested update is from customer feedback or a Community slack conversation, provide a link:

Many customers burned their fingers with this. Fixing the HELM was a urgent CS issue.

### Additional notes

Redpanda crew to talk to: @joejulian (HELM maintainer), @vuldin 
Relevant PRD: https://docs.google.com/document/d/1Qam-lXj-tW_yFc8qFV8S_FuMr2BHaUaj0lSlI4dOpOM/edit#

**Comment by Feediver1** [comment]
Hi @JakeSCahill Not seeing any recent updates here. Should this be an epic? Can you add a quick statement here about current status? Thx.

**Comment by JakeSCahill** [comment]
Ah, I think this is actually in review. I've covered the new Helm chart in:

- https://github.com/redpanda-data/documentation/pull/969
- https://github.com/redpanda-data/documentation/pull/968
- https://github.com/redpanda-data/documentation/pull/946
- https://github.com/redpanda-data/documentation/pull/920

**Comment by JakeSCahill** [comment]
@vladoschreiner can you confirm that these above PRs cover this issue? They edit what were the existing docs at the time and add additional docs.

**Comment by vladoschreiner** [comment]
LGTM.
