### ISSUE TITLE
1Q 2023: Request - Include console in the Quickstart journey

### ISSUE THREAD

**Issue by vladoschreiner** [redpanda-data/documentation#593]
### Describe the Issue

Console has been Redpandafied. It's a great tool to support product evaluation. We want to make sure that it becomes part of the get started experience. 

Audience: quickstart users.

Success criteria: once quickstart quideline is completed, the user has Console up and running in their setup and can use it to look around and do some streaming!

### Updates to existing documentation

Add Console to the existing quickstart guidelines.

One of the conclusions of the quickstarts should be user overlooking their new Redpanda cluster from the comfortable console UI.

### If the requested update is from customer feedback or a Community slack conversation, provide a link:

https://redpandadata.slack.com/archives/C02RQPX6A1K/p1661379401156139

### Additional notes

Contributors to talk to: @weeco , @rikimaru0345

**Comment by Feediver1** [comment]
From duplicate (closed #730 ):

The console installation manual has been moved to a dedicated install section, but we're lacking a bit of background to it.
It's important to add:

What the Redpanda Console is
When/why users need to install it
It's a good idea to take this opportunity to better stylize the page and follow other pages design. For example, we should use tabs to refer to different OSs.

Link to the Preview that moved Redpanda Console install:
[about](https://deploy-preview-722--redpanda-documentation.netlify.app/docs/quickstart/console-installation/)

Example for the tabs feature
https://github.com/redpanda-data/documentation/blob/dev/docs/quickstart/quick-start-linux.mdx

Additionally, the Docker install doc that tells users how to set up a 3-node cluster should include guidance on RP Console. For example, set up cluster, then install Console...see https://github.com/redpanda-data/documentation/issues/666 and https://github.com/redpanda-data/documentation/issues/665 and close these tickets as a duplicates when this is fixed.

**Comment by Feediver1** [comment]
@JakeSCahill I think we have a few duplicates wrt this request. I've assigned all tickets related to Console install to you, and included under the epic for Create new RP Quickstart. Close duplicates/use tickets you want as you see fit.

**Comment by JakeSCahill** [comment]
@Feediver1 WRT#665, should we have a separate quickstart for Enterprise users, or should we use headings such as Open Source Quickstart and Enterprise Quickstart?
