### ISSUE TITLE
3Q 22.3: Archive Data archiving (related to Tiered Storage)

### ISSUE THREAD

**Issue by daisukebe** [redpanda-data/documentation#596]
### Describe the Issue

https://docs.redpanda.com/docs/data-management/data-archiving/ has some issues

* Data archiving is exactly the same functionality as remote.write in Tiered Storage, hence duplicated
* We don't want to offer Data archiving so hard. Instead, users should use Tiered Storage
* Since 22.3, it will be very easy for a user to accidentally delete data in cloud by setting a retention.[ms|bytes] on their topic. Thus Data archiving feature is not really a solution that a user is looking for.

### Updates to existing documentation

The exact decision isn't made yet, but there are a couple of options.

* Archive the page completely with the release of v22.3 (likely)
* Mention a use case in the Tiered Storage page (less likely)
  * we should also mention that the data will be automatically deleted per the retention policy defined in the Redpanda cluster

### New feature or content gap requests

The new feature in v22.3 is documented in https://github.com/redpanda-data/core-internal/issues/17 

### Additional notes

In #product: https://redpandadata.slack.com/archives/C02FSLH3ZS9/p1660528343019469
In #docs: https://redpandadata.slack.com/archives/C01LK3UK2K1/p1660831838778069

Involving @mattschumpert and @mmedenjak

**Comment by daisukebe** [comment]
This and https://github.com/redpanda-data/documentation/issues/605 are related each other.

**Comment by Feediver1** [comment]
@mattschumpert Would this be a first entry for a new Deprecated Features section? Or should it simply be removed altogether?

**Comment by Feediver1** [comment]
Reminder: to add redirects, and also to suss out all the links into this topic from other topics.
