### ISSUE TITLE
3Q 22.3: Document two-stage bootstrap

### ISSUE THREAD

**Issue by mattschumpert** [redpanda-data/documentation#600]
Document new two-stage bootstrap procedure and the related changes simplifying node-level configuration of seed servers

- https://github.com/redpanda-data/core-internal/issues/14

Sub-issues
- redpanda-data/redpanda/issues/333
- redpanda-data/redpanda/issues/2793

**Comment by rkruze** [comment]
We will want to make sure we update all the quickstart as this will impact the way we launch via docker compose. Also for installing manually. We will also want to update the reference section that talks about configuring `node_id`.
