### ISSUE TITLE
3Q 22.3: Document support for compacted Tiered Storage topics

### ISSUE THREAD

**Issue by mattschumpert** [redpanda-data/documentation#604]
- redpanda-data/core-internal/issues/23

When we implement compaction for tiered storage topics, the approach to compaction will be more nuanced than with regular topics and needs to be documented.  In general we don't document how compaction works (possibly because it's the same as Kafka), but in this case it will be done in a particular way if the topic is a Tiered Storage topic.

**Comment by mattschumpert** [comment]
This describes what's being implemented;: https://docs.google.com/document/d/1wsQDDe0O5LHolRVJbDrUjSL1BfhaarTGHg7fvlxqGyY/edit#heading=h.w0pb7rtb9hph

**Comment by Feediver1** [comment]
@micheleRP Was this issue addressed in 22.3? If so, please close. Thx.

**Comment by micheleRP** [comment]
@Feediver1 yes, this was addressed with https://github.com/redpanda-data/documentation/pull/709#pullrequestreview-1169267164. Not sure why it didn't close on its own.
