### ISSUE TITLE
3Q 22.3: Document new tiered storage retention controls

### ISSUE THREAD

**Issue by mattschumpert** [redpanda-data/documentation#605]
- https://github.com/redpanda-data/core-internal/issues/17

New Tiered Storage topic config settings for retention control in cloud and local storage.
redpanda-data/redpanda/issues/4050

related to #596

**Comment by micheleRP** [comment]
This was resolved with https://github.com/redpanda-data/documentation/pull/709#pullrequestreview-1169267164. Not sure why it didn't close on its own with that PR.
