### ISSUE TITLE
1Q 23.1: Document new Kafka API support: AlterPartitionAssignments and ListPartitionReassignments

### ISSUE THREAD

**Issue by mattschumpert** [redpanda-data/documentation#606]
- https://github.com/redpanda-data/core-internal/issues/25

Implemented in /redpanda-data/redpanda/issues/1227

Our Kafka compatibility page should mention these are now directly supported (vs using convoluted Admin API commands). This will support a feature in Console but is generally useful

**Comment by Feediver1** [comment]
@mattschumpert Can you confirm that this feature is no longer scoped for 22.3.1? Thanks.

**Comment by mattschumpert** [comment]
@Feediver1 
This is happening as planned in 23.1.

We should also note that custom assignment IS possible at topic creation time (contrary to previous thinking). See https://github.com/redpanda-data/redpanda/issues/1460 for details on that one.  A small section of a page relating to advanced use cases (custom partition assignment) covering both the create and the move (AlterPartitionAssignments) is needed.

**Comment by micheleRP** [comment]
Changing to P1 feature per [roadmap ](https://docs.google.com/spreadsheets/d/1M1UZxe1WYdROKnDrPiWPohwJ25lW-De-MEMQWutH4Kk/edit#gid=1853463140)

**Comment by micheleRP** [comment]
Hi @NyaliaLui! Some questions for you: 
- Do you think we should add a new section for this on the [Cluster Balancing](https://docs.redpanda.com/docs/manage/cluster-maintenance/cluster-balancing/) page? If not here, where do you think? 
- Is it correct that we should include examples of how to assign partitions at topic creation with the Kafka API, as well as listing & reassigning partitions with the Kafka API, the Admin API, and rpk?
- Do you have any guidelines yet about how reassignments work with default cluster balancing or Continuous Data Balancing?

**Comment by NyaliaLui** [comment]
Following the docs issue template:

### Describe the Issue

**What problem does this issue solve for customers?**
Apache Kafka does not come with a partition balancer by default so the AlterPartitionReassignments API is meant to give users control over where a partition lives. This means that there are many 3rd party tools, either private or opensource, in the Kafka ecosystem that control partition movement using the API.

Therefore, adding support for AlterPartitionReassignments API enables Redpanda to be compatibile with the tools that customers already use.

**Who is the audience for this update?**
Cluster admins, developers, and anyone that needs to implement their partition balancing algorithms.

**Do you know the context in which users will likely search for this content?**
I would expect users to search for this API in the context of partition balancing.

### Updates to existing documentation

We should probably have a subsection in the [Cluster Balancing page](https://docs.redpanda.com/docs/manage/cluster-maintenance/cluster-balancing/) as an alternative to auto balancing and Continuous Data Balancing. This would be a good location to include examples of how to issue AlterPartitionReassignments and ListPartitionReassignments requests. In this section we should also note that we do not make gaurantees between the partition auto balancer and AlterPartitionReassignments requests. Specifically, if the balancer is turned on, then it may change partition assignments regardless of an AlterPartitionReassignments request.

I'll update the ticket with examples next week.


### New feature or content gap requests

AlterPartitionReassignments and ListPartitionReassignments is originally proposed in [KIP-455](https://cwiki.apache.org/confluence/display/KAFKA/KIP-455%3A+Create+an+Administrative+API+for+Replica+Reassignment) and that served as the first design guideline for adding this support to Redpanda

An online example of how to use this API with Kafka's reassign partitions script https://strimzi.io/blog/2022/09/16/reassign-partitions/

### If new feature, in which release is it included or expected?

Expected for v23.1


### Additional notes

Several discussions occurred on slack,
- Thread on initial development - https://redpandadata.slack.com/archives/C03UV0TS9C3/p1669649914293489
- Thread on even replication factor - https://redpandadata.slack.com/archives/C04B5T58QQ1/p1675196399050039
- Some semantics on canceling an AlterPartitionReassignment request - https://redpandadata.slack.com/archives/C04B5T58QQ1/p1675379671475609?thread_ts=1674785563.699929&cid=C04B5T58QQ1

**Comment by NyaliaLui** [comment]
@micheleRP Here you go :) 

> Hi @NyaliaLui! Some questions for you:
> 
>     * Do you think we should add a new section for this on the [Cluster Balancing](https://docs.redpanda.com/docs/manage/cluster-maintenance/cluster-balancing/) page? If not here, where do you think?

I think this page is fine.
 
>     * Is it correct that we should include examples of how to assign partitions at topic creation with the Kafka API, as well as listing & reassigning partitions with the Kafka API, the Admin API, and rpk?

Yes we should include examples but AlterPartitionReassignments/ListPartitionReassignments is not suppored in `rpk` yet. I'll provide examples next week.

>     * Do you have any guidelines yet about how reassignments work with default cluster balancing or Continuous Data Balancing?

The engineering team has not yet reached concensus on how AlterPartitionReassignments and ListPartitionReassignments interacts with the partition balancer. So for now we should simply document that if the balancer is turned on, then it may overrule an AlterPartitionReassignment.

**Comment by NyaliaLui** [comment]
@micheleRP here are the examples we can use for this docs post

1. Show initial replica sets for topic `foo` with `rpk`
```bash
rpk topic describe foo -p
PARTITION  LEADER  EPOCH  REPLICAS  LOG-START-OFFSET  HIGH-WATERMARK
0          1       1      [1 2 3]   0                 645
1          1       1      [0 1 2]   0                 682
2          3       1      [0 1 3]   0                 672
```

2. We need to put all partition reassignments in a json file before we issue the request. For example, suppose we want to replace node 0 with another in the replica sets of partitions 1 and 2. The json file would look like:
```json
{
  "version": 1,
  "partitions": [
    {
      "topic": "foo",
      "partition": 1,
      "replicas": [
        3,
        1,
        2
      ]
    },
    {
      "topic": "foo",
      "partition": 2,
      "replicas": [
        2,
        1,
        3
      ]
    }
  ]
}

```

3. We can execute partition reassignments with the `kafka-reassign-partitions.sh` script where `example.json` is the name of the json file we created in step 2
```bash
kafka-reassign-partitions.sh --bootstrap-server localhost:9092,localhost:9093,localhost:9094,localhost:9095 --reassignment-json-file example.json --execute
Current partition replica assignment

{"version":1,"partitions":[{"topic":"foo","partition":1,"replicas":[1,2,0],"log_dirs":["any","any","any"]},{"topic":"foo","partition":2,"replicas":[3,1,0],"log_dirs":["any","any","any"]}]}

Save this to use as the --reassignment-json-file option during rollback
Successfully started partition reassignments for foo-1,foo-2
```

4. We can check if the reassignment is complete with the flags `--verify --preserve-throttles`. For details on why `--preserve-throttles` is necessary, see the section "Differences between Redpanda and Kafka".
```bash
kafka-reassign-partitions --bootstrap-server localhost:9092,localhost:9093,localhost:9094,localhost:9095 --reassignment-json-file sample.json --verify --preserve-throttles
Status of partition reassignment:
Reassignment of partition foo-1 is complete.
Reassignment of partition foo-2 is complete.
```

5. Alternatively, you could run `rpk` again to verify the replica sets
```bash
rpk topic describe foo -p
PARTITION  LEADER  EPOCH  REPLICAS  LOG-START-OFFSET  HIGH-WATERMARK
0          3       2      [1 2 3]   0                 0
1          2       2      [1 2 3]   0                 0
2          2       1      [1 2 3]   0                 0
```

**Comment by NyaliaLui** [comment]
We should also include a section on the differences between our implementation and Kafka's. Here is the list of differences I have now, it will likely be updated over the next few days. For more context, see [this slack thread](https://redpandadata.slack.com/archives/C04AVDG7N58/p1675807169036569?thread_ts=1675804758.947049&cid=C04AVDG7N58).

1. With Kafka, users can issue AlterPartitionReassignments requests to upreplicate or dereplicate a topic partition. However, this is currently unsupported in Redpanda.

2. Redpanda supports shard-level partition assignments. Therefore, when resolving an AlterPartitionReassignments request, Redpanda will automatically determine the shard placements. If users want a topic-partition on a specific shard, they will need to go through the Admin API

3. Kafka comes with a shell script to issue AlterPartitionReassignments requests, `kafka-reassign-partitions.sh`. This script will attempt to use some throttle configs that Redpanda does **not** support, such as `replica.alter.log.dirs.io.max.bytes.per.second`. Therefore, it is important to use the flag `--preserve-throttles` so the script does **not** attempt to change those configs. Otherwise `kafka-reassign-partitions.sh` may report errors.

4. An AlterPartitionReassignment request lists the ids for each replica. Kafka will validate the node id for **any new replica** (one that is not in the previous replica set) against the list of alive nodes. Redpanda will validate **all replicas** against the list of alive nodes

5. In a scenario where there are two identical AlterPartitionReassignment requests. Redpanda will reject one of them with the error `no_reassignment_in_progress`
