### ISSUE TITLE
Confirm organization of the Deployment doc section

### ISSUE THREAD

**Issue by micheleRP** [redpanda-data/documentation#617]
As part of our quality edits post 22.2, we realized that the Deployment section needs a more substantive review. See https://docs.redpanda.com/docs/deployment/

Questions for this section:

- Should these doc topics be reordered? Deploying for Production comes last, but should it move closer to the 1st topic Using Terraform & Ansible to Deploy Redpanda?
- Can these 2 topics be consolidated (or maybe move sample into the Reference section): Using Configuration Parameters with a Custom Resource & Using Additional Configuration Parameters
- Should Managing Disk Space move into the Cluster Administration section?
- Should Optimizing I/O move to the end?

**Comment by Feediver1** [comment]
This should be handled in https://github.com/redpanda-data/documentation/issues/792
