### ISSUE TITLE
Tiered Storage AWS docs include outdated info

### ISSUE THREAD

**Issue by dariagrudzien** [redpanda-data/documentation#620]
### Describe the Issue

When trying to enable shadow indexing I've ran into a note in the doc which doesn't seem to apply anymore. 

### Updates to existing documentation

URL: https://docs.redpanda.com/docs/data-management/tiered-storage/#configuring-amazon-s3
Part to update: point 1 (`Specify the expiration rules for the files that are based on the rp-type file tags.`) According to @esteban this is no longer required and related docs no longer exist ([1](https://github.com/redpanda-data/redpanda/pull/864/commits/e7cedc7df862619cf35c5903dc6a2ceb37826589) & [2](https://github.com/redpanda-data/redpanda/pull/864/commits/e7cedc7df862619cf35c5903dc6a2ceb37826589#diff-8bfaf45b9598ae430d7a7275ca2b47b2e97f1fee0074841e9d80dee2f5aa5b25R50-R55)) @Lazin may be able to provide more context.

**Comment by Feediver1** [comment]
@dariagrudzien @micheleRP Best I can tell, this material is no longer in the doc. I am closing. If you think this content still requires an update, please re-open. Thx.
