### ISSUE TITLE
Flags new-username and new-password are deprecated for acl user create

### ISSUE THREAD

**Issue by Scandiravian** [redpanda-data/documentation#626]
### Describe the Issue

The section `rpk for managing users and ACLs` has a command that uses deprecated flags

### Updates to existing documentation

https://docs.redpanda.com/docs/manage/security/authorization/#rpk-for-managing-users-and-acls

For the command `rpk acl user create` in [rpk for managing users and ACLs](https://docs.redpanda.com/docs/security/authorization/#rpk-for-managing-users-and-acls) the flags `--new-username` and `--new-password` are deprecated. The command should instead be `rpk acl user create Jack --password <password> --api-urls localhost:9644`

I think this is relevant for both version `22.2` and `22.1`

**Comment by Feediver1** [comment]
Seems related to https://github.com/redpanda-data/documentation/issues/815 and/or https://github.com/redpanda-data/documentation/issues/997
