### ISSUE TITLE
Add single quote for passwords to accommodate complex passwords (special chars)

### ISSUE THREAD

**Issue by larsenpanda** [redpanda-data/documentation#632]
### Describe the Issue

If a user needs to create an account (and use that account) with a complex password with special characters, it needs to be single quoted, with rpk (on user create and password usage in commands) and inside of the yaml definitions whenever referenced. 

### Updates to existing documentation

I think it would be sufficient to change all locations where passwords are referenced or set in any commands or configurations to be single quoted, it's just good practice.

In the security section of the documentation, maybe point out that docs throughout will reference the password as single quoted because of potential special characters.

**Comment by micheleRP** [comment]
Status: Estimate increased for testing. Moving this to the next sprint.
