### ISSUE TITLE
Cloud v1 Overview - Dedicated vs BYOC

### ISSUE THREAD

**Issue by bpraseed** [redpanda-data/documentation#648]
### Describe the Issue

As a redpanda user who is looking to learn details on the difference between dedicated (previously FMC)  vs BYOC architecture and benefits.

### Updates to existing documentation

N/A

### New feature or content gap requests
Gap
https://docs.google.com/presentation/d/130hk_zJbvKETB8zMK7II6TH8Il3D9fxOUKWoonxnJXM/edit#slide=id.g147cbc69730_0_139

**Comment by AnneLeeperRP** [comment]
Closing this issue, since #662 was created for Cloudv2 and contains more info.
