### ISSUE TITLE
UX Improvement: Keep search box at the top even scrolling down to the bottom

### ISSUE THREAD

**Issue by daisukebe** [redpanda-data/documentation#650]
### Describe the Issue

In a given page, after scroll down to the bottom the search bar disappears and doesn't show up until scrolling up to the top. I'd propose to always show up the search box. Here's one example on Chrome Version 105.0.5195.102 (Official Build) (64-bit). Firefox 104.0.2 (64-bit) does the same. Both browsers are running on Ubuntu.

At first when the scroll bar is at the top, the search box appears:
![image](https://user-images.githubusercontent.com/350206/190320388-dca700fe-86a2-40e9-9ed5-9bc49d582550.png)

It's still there even scrolling down to the middle of the page:
![image](https://user-images.githubusercontent.com/350206/190320468-59ce8a45-753f-487c-81d2-ef18a1efb5b7.png)

It disappears once the scroll bar reaches the bottom:
![image](https://user-images.githubusercontent.com/350206/190320536-74ce9d72-a1da-4232-a753-e83ae425aca5.png)

Scroll up to the middle, but half of the search box has shown up:
![image](https://user-images.githubusercontent.com/350206/190320637-b9e2932e-8ee2-4566-bb11-37320c43a139.png)

Reach out to the top of the page, and finally the search box fully reappears:
![image](https://user-images.githubusercontent.com/350206/190320715-a269cd7c-f15e-445a-8c9d-39f33ffc5207.png)

> What problem does this issue solve for customers?

Make search docs easier

> Who is the audience for this update? For example, Infosec admins, cluster admins, or developers.

Any document readers

### Updates to existing documentation

> Provide the URL of the page(s) to which the updates apply.

Any page

**Comment by Feediver1** [comment]
I think this is a duplicate of https://github.com/redpanda-data/documentation/issues/439. If you concur, let's close one of these as a duplicate. Thx.

**Comment by daisukebe** [comment]
Looks like so. Thank you.
