### ISSUE TITLE
Disk Handling verbiage needs more verbose clarity, perhaps an example.

### ISSUE THREAD

**Issue by larsenpanda** [redpanda-data/documentation#651]
### Describe the Issue

This isn't totally clear, please add more verbiage to help us understand:

> The storage_min_free_bytes configuration field determines the threshold of free space–the hard limit–for this write rejection.
https://docs.redpanda.com/docs/deployment/disk-utilization/#handle-full-disks

### Updates to existing documentation

I'm not sure the best way to rephrase this at the moment, an example would probably be helpful.

**Comment by Feediver1** [comment]
@piyushredpanda Can anyone on your team act as SME and provide a "real world" example for the writer to add? Thx!

**Comment by piyushredpanda** [comment]
@Feediver1: We could go with John Spray, but I'm a little confused by the need for help on a real world example. Sounds like a relatively simple thing that doc team could take a stab at and seek SME's help to review?
