### ISSUE TITLE
Customer Feedback: Update Docker Compose address

### ISSUE THREAD

**Issue by AnneLeeperRP** [redpanda-data/documentation#659]
### Describe the Issue

See email to docs on Sept 21, 2022 at 3:23PM PDT.
Customer feedback on Docker Compose address.
From: Jason Hancock (jason@jasonhancock.com)

### Updates to existing documentation

Link to doc: https://docs.redpanda.com/docs/quickstart/quick-start-docker/#bring-up-a-docker-compose-file

Topic to update: Bring up a docker-compose file

Description from the customer's email:

The docker-compose instructions https://docs.redpanda.com/docs/quickstart/quick-start-docker/#bring-up-a-docker-compose-file don't work. You have to update the "localhost:9092" to "redpanda:9092" for both the 
--advertise-kafka-addr and --advertise-pandaproxy-addr flags.

Otherwise, if you try to do something like run a container to bootstrap rpk topics, you end up getting a "cannot connect to [127.0.0.1:9092](http://127.0.0.1:9092/)" error.

#### This will fail:

version: "3.9"
services:
  redpanda:
    image: [docker.redpanda.com/vectorized/redpanda:v22.2.3](http://docker.redpanda.com/vectorized/redpanda:v22.2.3)
    container_name: redpanda-1
    command:
    - redpanda
    - start
    - --smp
    - '1'
    - --reserve-memory
    - 0M
    - --overprovisioned
    - --node-id
    - '0'
    - --kafka-addr
    - PLAINTEXT://[0.0.0.0:29092](http://0.0.0.0:29092/),OUTSIDE://[0.0.0.0:9092](http://0.0.0.0:9092/)
    - --advertise-kafka-addr
    - plaintext://redpanda:29092,OUTSIDE://localhost:9092
    - --pandaproxy-addr
    - PLAINTEXT://[0.0.0.0:28082](http://0.0.0.0:28082/),OUTSIDE://[0.0.0.0:8082](http://0.0.0.0:8082/)
    - --advertise-pandaproxy-addr
    - plaintext://redpanda:28082,OUTSIDE://localhost:8082
    ports:
    - 8081:8081
    - 8082:8082
    - 9092:9092
    - 28082:28082
    - 29092:29092
    expose:
    - "9092"

  redpandasetup:
    image: [docker.redpanda.com/vectorized/redpanda:v22.2.3](http://docker.redpanda.com/vectorized/redpanda:v22.2.3)
    depends_on:
      - redpanda
    restart: "no"
    environment:
      REDPANDA_BROKERS: redpanda:9092
    entrypoint: sh -c "sleep 3 && rpk topic create incoming"

#### This will work:

version: "3.9"
services:
  redpanda:
    image: [docker.redpanda.com/vectorized/redpanda:v22.2.3](http://docker.redpanda.com/vectorized/redpanda:v22.2.3)
    container_name: redpanda-1
    command:
    - redpanda
    - start
    - --smp
    - '1'
    - --reserve-memory
    - 0M
    - --overprovisioned
    - --node-id
    - '0'
    - --kafka-addr
    - PLAINTEXT://[0.0.0.0:29092](http://0.0.0.0:29092/),OUTSIDE://[0.0.0.0:9092](http://0.0.0.0:9092/)
    - --advertise-kafka-addr
    - plaintext://redpanda:29092,OUTSIDE://redpanda:9092
    - --pandaproxy-addr
    - PLAINTEXT://[0.0.0.0:28082](http://0.0.0.0:28082/),OUTSIDE://[0.0.0.0:8082](http://0.0.0.0:8082/)
    - --advertise-pandaproxy-addr
    - plaintext://redpanda:28082,OUTSIDE://redpanda:8082
    ports:
    - 8081:8081
    - 8082:8082
    - 9092:9092
    - 28082:28082
    - 29092:29092
    expose:
    - "9092"

  redpandasetup:
    image: [docker.redpanda.com/vectorized/redpanda:v22.2.3](http://docker.redpanda.com/vectorized/redpanda:v22.2.3)
    depends_on:
      - redpanda
    restart: "no"
    environment:
      REDPANDA_BROKERS: redpanda:9092
    entrypoint: sh -c "sleep 3 && rpk topic create incoming"

**Comment by tmgstevens** [comment]
We should not be asking people to edit the hosts file - the `ports` section in the docker-compose should map the internal ports (9092 etc) to the port on the host machine.

To interact with the cluster you have two options:
1. Use a locally installed rpk:
```
➜  docker-compose-test rpk cluster status --brokers localhost:9092
CLUSTER
=======
redpanda.f1bfc640-fa41-4034-890c-eee50a82a584

BROKERS
=======
ID    HOST       PORT
0*    localhost  9092

➜  docker-compose-test rpk topic create mytopic --brokers localhost:9092
TOPIC    STATUS
mytopic  OK
➜  docker-compose-test rpk topic produce mytopic --brokers localhost:9092
hello
Produced to partition 0 at offset 0 with timestamp 1670931674466.
^C
➜  docker-compose-test rpk topic consume mytopic --brokers localhost:9092
{
  "topic": "mytopic",
  "value": "hello",
  "timestamp": 1670931674466,
  "partition": 0,
  "offset": 0
}
```
3. Use a docker exec to run rpk within the container 
```
➜  docker-compose-test docker exec -it redpanda-1 rpk cluster status
CLUSTER
=======
redpanda.f1bfc640-fa41-4034-890c-eee50a82a584

BROKERS
=======
ID    HOST      PORT
0*    redpanda  29092

TOPICS
======
NAME     PARTITIONS  REPLICAS
mytopic  1           1

➜  docker-compose-test docker exec -it redpanda-1 rpk topic create mynewtopic2
TOPIC        STATUS
mynewtopic2  OK
➜  docker-compose-test docker exec -it redpanda-1 rpk topic produce mynewtopic2
hello
Produced to partition 0 at offset 0 with timestamp 1670931763323.
^C%
➜  docker-compose-test docker exec -it redpanda-1 rpk topic consume mynewtopic2
{
  "topic": "mynewtopic2",
  "value": "hello",
  "timestamp": 1670931763323,
  "partition": 0,
  "offset": 0
}
^C%
```

@AnneLeeperRP we should add a section to document these commands.

**Comment by AnneLeeperRP** [comment]
Closing this issue based on advice from @tmgstevens 
Will create a new issue for the commands that need to be documented (outlined in Tristan's comment, above).
