### ISSUE TITLE
Cloudv2 Overview

### ISSUE THREAD

**Issue by AnneLeeperRP** [redpanda-data/documentation#662]
### Describe the Issue

The Cloudv2 documentation needs an overview to explain the differences between "Dedicated" (the new name for FMC) and "BYOC". Show architecture and benefits.

### New feature or content gap requests

Link to Praseed's slide preso with architecture diagrams and other background info:
https://docs.google.com/presentation/d/130hk_zJbvKETB8zMK7II6TH8Il3D9fxOUKWoonxnJXM/edit#slide=id.g147cbc69730_0_364

### If new feature, in which release is it included or expected? 

Cloudv2 will have a beta1 release scheduled for Tuesday, Oct. 11th.

### Additional notes

The main issue with all the sections outlined is #649.

**Comment by Feediver1** [comment]
@AnneLeeperRP Is this a duplicate of https://github.com/redpanda-data/documentation/issues/648? If so, let's close one as a duplicate. Thx

**Comment by AnneLeeperRP** [comment]
This issue can be closed, since PR 699 is merged.
