### ISSUE TITLE
Make Docker compose reference more prominent in Redpanda Console Installation docs

### ISSUE THREAD

**Issue by weeco** [redpanda-data/documentation#664]
### Describe the Issue

From this slack thread: https://redpandadata.slack.com/archives/C01LK3UK2K1/p1663859660106979
about this documentation page: https://docs.redpanda.com/docs/console/installation/

Roko Kruze (PDT)
  [4 days ago](https://redpandadata.slack.com/archives/C01LK3UK2K1/p1663859816574739?thread_ts=1663859660.106979&cid=C01LK3UK2K1)
I know we reference to the docker compose in the Note section, but the link to the Docker compose on there is so subtle it doesn’t make it clear that a user needs to go there to get that info

Roko Kruze (PDT)
  [4 days ago](https://redpandadata.slack.com/archives/C01LK3UK2K1/p1663860143684209?thread_ts=1663859660.106979&cid=C01LK3UK2K1)
From the wording it doesn’t make it clear that behind that link is the way to run console along with Redpanda

Roko Kruze (PDT)
  [4 days ago](https://redpandadata.slack.com/archives/C01LK3UK2K1/p1663860160654699?thread_ts=1663859660.106979&cid=C01LK3UK2K1)
When I first looked at this page I skipped over that completely

### Additional notes

Because of the note about the docker host parameter that is only supported on Linux machines, people assume that Console doesn't run on Mac computers. This is not the case. We need to make this clearer

**Comment by AnneLeeperRP** [comment]
Submitted [PR 759](https://github.com/redpanda-data/documentation/pull/759). Tagged @weeco for review.

**Comment by weeco** [comment]
@AnneLeeperRP I think this is not sufficient. Even though @rkruze is the request and I was only asked to file that issue on his behalf, I agree to that request and in my opinion it should be more prominent than just a sentence in the note section. It's the best option to quickly getting started and play around with Console on a local machine, and thus deserves a little more attention I'd say.

**Comment by AnneLeeperRP** [comment]
@weeco  I was thinking the same thing. I can create two separate headings: one for Linux systems and one for MacOS, etc. That way, users can look for the instructions for their OS. Sound good?

**Comment by rkruze** [comment]
Longer term we should have the console integrated with the other docs. For example: https://docs.redpanda.com/docs/quickstart/quick-start-docker/#set-up-a-three-node-cluster should include the console. Same with the following: https://docs.redpanda.com/docs/quickstart/quick-start-linux/
