### ISSUE TITLE
cloud: Add documentation BYOC

### ISSUE THREAD

**Issue by sameers361** [redpanda-data/documentation#67]
Add documentation on the end-to-end workflow for creation of a BYOC cluster.  This should be independent of the UX
1) Create cluster
2) Dowload zip file
3) Add credentials
4) Run terraform
5) Check deployment status

@sameers361 will provide more details

**Comment by Deflaimun** [comment]
Closed as completed
https://docs.redpanda.com/docs/deploy/deployment-option/cloud/dedicated-byoc/
