### ISSUE TITLE
Customer feedback: Remove __consumer_offsets Note from 22.1 docs (only)

### ISSUE THREAD

**Issue by Feediver1** [redpanda-data/documentation#672]
### Describe the Issue

Feedback from a prospect (see Slack post in #docs):
https://redpandadata.slack.com/archives/C01LK3UK2K1/p1663956318281419

A prospect nAuto pointed this to me as they got confused. Thought we had support for `__consumer_offsets`  since V22.1.

Remove this statement from https://docs.redpanda.com/docs/data-management/data-migration/#run-mirrormaker-to-start-replication 
**_for the 22.1 version only_**.

![image (2)](https://user-images.githubusercontent.com/102751339/192555521-4359404d-59e8-46d0-845e-b23a0046901d.png)

**Comment by Deflaimun** [comment]
Tagging this issue as blocked since it didn't received any reviews yet.
