### ISSUE TITLE
Add meta tag and script to doc header for SEO, site tracking

### ISSUE THREAD

**Issue by Feediver1** [redpanda-data/documentation#680]
### Describe the Issue

Marketing want to verify Docs in Google Search Console so they can monitor its performance in SEO. Please add the following meta tag to the html <head> on docs. This'll allow them to verify ownership in Google:

`<meta name="google-site-verification" content="QcL-pD81oJatgKXQ3Wquvk_Ku3RRtUljxKoMaicySQA" />`

A separate--but related request to the above--they would also like to add [Plausible.io](http://plausible.io/) to Docs in order to more accurately track traffic to the site (It's very privacy friendly, so it doesn't need to be behind the GDPR banner). Please aadd the following script also to the html <head>?

`<script defer data-domain="[redpanda.com](http://redpanda.com/)" src="https://plausible.io/js/plausible.js"></script>`

**Comment by Deflaimun** [comment]
@justincoons
