### ISSUE TITLE
Community Feedback-Request: Update regex example

### ISSUE THREAD

**Issue by Feediver1** [redpanda-data/documentation#683]
### Describe the Issue

Customer-reported issue wrt: https://deploy-preview-528--redpanda-documentation.netlify.app/docs/core/security/authentication/#configure-mtls-with-authentication

Redpanda Community Slack:
https://redpandacommunity.slack.com/archives/C01AJDUT88N/p1664549507642969

User: Fazir:
Hi everyone, when setting up authn/authz, is it strictly needed to use a SASL-authenticated superuser? Or is it possible using the mtls_identity authentication? Do I just declare whatever my kafka mtls principal-mapper will result in, as a superuser? I am having trouble setting up ACLs for my redpanda deployment. Running 22.2.2 on Ubuntu.

Seems I've found my issue..
The documentation gives examples where the principal mapper regex would only return the first character CN=([^,]).*, instead of what is being described, which worked for me: CN=([^,].*)
Didn't think to more closely examine the regex at first since I thought a copy paste of the example would do what was described by it. Might make a documentation issue on the github later

Please correct the regex example so customers can copy and paste it.

Thanks

**Comment by micheleRP** [comment]
SMEs = @NyaliaLui, @BenPope

**Comment by BenPope** [comment]
This fixed, right? https://github.com/redpanda-data/documentation/pull/821

**Comment by NyaliaLui** [comment]
> This fixed, right? #821

Took a 2nd look at #821 and that has the correct regex spelling.

**Comment by micheleRP** [comment]
Thank you @BenPope and @NyaliaLui!
