### ISSUE TITLE
Docs: Edit CLI text

### ISSUE THREAD

**Issue by coral-waters** [redpanda-data/documentation#69]
These files need to go through doc review: 
https://github.com/vectorizedio/redpanda/tree/dev/src/go/rpk/pkg/cli/cmd

@Deflaimun 's preview link with the cli text: 
https://deploy-preview-441--vectorizedio.netlify.app/docs/rpk-commands/

And the PR just in case: 
https://github.com/vectorizedio/www/pull/441

**Comment by Deflaimun** [comment]
Doesn't apply anymore
