### ISSUE TITLE
documentation for installing Console on Linux (on-prem) should detail how to start it

### ISSUE THREAD

**Issue by jason-da-redpanda** [redpanda-data/documentation#694]
### Updates to existing documentation
https://docs.redpanda.com/docs/console/installation/)

Which topic(s) should be updated?
Section :  **Binaries and Linux packages**

What is the requested fix?  
the guide tells customers/admins how to install console on linux..

But it does not detail how to start. This might be obvious to some, but we should include it.

This method of installation installs redpanda-console  as a service...

e.g  To see status. (also shows the config file being used ) 

sudo systemctl status   redpanda-console
`● redpanda-console.service - Redpanda Console is a developer-friendly UI for managing your Kafka/Redpanda workloads.
     Loaded: loaded (/lib/systemd/system/redpanda-console.service; disabled; vendor preset: enabled)
     Active: active (running) since Tue 2022-10-04 15:25:01 UTC; 1min 37s ago
       Docs: https://docs.redpanda.com
   Main PID: 42005 (redpanda-consol)
      Tasks: 7 (limit: 4689)
     Memory: 30.0M
        CPU: 617ms
     CGroup: /system.slice/redpanda-console.service
             └─42005 /usr/bin/redpanda-console -config.filepath /etc/redpanda/redpanda-console-config.yaml`

So to start as a service would be : 
sudo systemctl start redpanda-console

Is this request to document an existing Redpanda feature that is not currently documented?
No. Its just missing how to start 'redpanda console'  on linux

**Comment by Feediver1** [comment]
cc: @weeco Please add any guidance/feedback that might help @AnneLeeperRP with this request. Thanks!

**Comment by weeco** [comment]
I think Jason put the response how to start and check status into his issue.

> So to start as a service would be :
sudo systemctl start redpanda-console

> e.g To see status. (also shows the config file being used )
sudo systemctl status redpanda-console

I think it's worth highlighting where configuration changes (e.g. to edit connection details) can be made. As Jason said this can be looked up via the status command, but for those who don't want to look it up, the config file is here: `/etc/redpanda/redpanda-console-config.yaml` and all config.yaml configurations that are documented (e.g. in the reference config) would go into that file.

**Comment by AnneLeeperRP** [comment]
Thank you @jason-da-redpanda and @weeco for the detailed information!

**Comment by JakeSCahill** [comment]
we'll be putting the Linux install instructions into the production deployment guide for Linux: https://docs.redpanda.com/docs/platform/deployment/production-deployment/
