### ISSUE TITLE
Customer Feedback: Remove duplicate text in --brokers flag in rpk-debug-bundle command doc

### ISSUE THREAD

**Issue by Feediver1** [redpanda-data/documentation#696]
### Describe the Issue

Customer feedback via link on this page:

Doc url: https://docs.redpanda.com/docs/reference/rpk/rpk-debug/rpk-debug-bundle/

The description for --brokers flag has duplicated text: 

Alternatively, you may set the REDPANDA_BROKERSenvironment variable with the comma-separated list of broker addresses.. Alternatively, you may set the REDPANDA_BROKERS environment variable with the comma-separated list of broker addresses

@twmb Is this on our side or in the actual CLI code? Thx.

When fixed, circle back to customer/respond to email of Sept 29, 2022 3:35 AM from jonathon@streamkap.com

**Comment by Feediver1** [comment]
@twmb Fixed this on docs side - can you fix on the code side? Thanks!

**Comment by r-vasquez** [comment]
I can confirm that it's not there on v22.3.9:

```
$ rpk version
v22.3.9 (rev a7d8697)

➜  ~ rpk debug bundle -h
'rpk debug bundle' collects environment data that can help debug and diagnose
issues with a redpanda cluster, a broker, or the machine it's running on. It
then bundles the collected data into a zip file.

<REDACTED>

Usage:
  rpk debug bundle [flags]

Flags:
      <REDACTED>
      --brokers strings                   Comma-separated list of broker ip:port pairs (e.g. --brokers '192.168.78.34:9092,192.168.78.35:9092,192.179.23.54:9092'). Alternatively, you may set the REDPANDA_BROKERS environment variable with the comma-separated list of broker addresses
      <REDACTED>

Global Flags:
  -v, --verbose   Enable verbose logging (default: false)

```

cc: @Deflaimun

**Comment by Feediver1** [comment]
Thanks @r-vasquez !
