### ISSUE TITLE
Create rpk installation topic under Install and Upgrade

### ISSUE THREAD

**Issue by Feediver1** [redpanda-data/documentation#698]
### Describe the Issue

There is no stand-along rpk install doc. Currently, this information only exists in the https://docs.redpanda.com/docs/quickstart/quick-start-macos/#install-rpk topic.

Other features rely on this installation as a prerequisite. For example, this install is a prerequisite in the new cloud topic coming in 22.3.1: Creating a cluster" (step 4: Deploy agent will not work unless the user has installed rpk). Hence, it needs to be added as a standalone topic. 
Under the Install and Upgrade H1 in the navtree, please add a new topic: "Installing rpk"

Use the same instructions that appear in https://docs.redpanda.com/docs/quickstart/quick-start-macos/#install-rpk

cc: @AnneLeeperRP Please work with @Deflaimun  review this PR. Also, please add the appropriate SMEs/eng reviewers. Anne--what about other platforms, such as the default (linux) and k8s? This content must work for those platforms too.

**Comment by Deflaimun** [comment]
Blog post on this topic
https://redpanda.com/blog/rpk-command-line-interface-developer-productivity
