### ISSUE TITLE
60 second guides should be indented under 'install' docs section/

### ISSUE THREAD

**Issue by mattschumpert** [redpanda-data/documentation#701]
These are really our install guides yet somehow they got moved up the tree as a sibling of 'install', but BELOW and this looks confusing to folks, including Customers Success

These guides should be early and WITHIN the 'install & upgrade' doc tree.

@micheleRP , @rkruze 

<img width="290" alt="Screen Shot 2022-10-08 at 8 39 51 AM" src="https://user-images.githubusercontent.com/103140945/194715696-49fb7e6d-d4e6-4d3d-9fa7-b2c676323c81.png">

**Comment by Feediver1** [comment]
This is going to be covered by #713 Closing as a duplicate
