### ISSUE TITLE
Update guidance on `rpk generate grafana-dashboard` for `public_metrics`

### ISSUE THREAD

**Issue by VladLazar** [redpanda-data/documentation#702]
### Describe the Issue

The [monitoring page](https://docs.redpanda.com/docs/cluster-administration/monitoring) currently guides users to not use
rpk for generating grafana dashboards when using the public_metrics endpoint. This guidance was required for the v22.2 release
because we did not yet have rpk support for it. Since v22.2.3 this has changed and `rpk generate grafana-dashboard` works with `public_metrics` too.

### Updates to existing documentation

The [monitoring page](https://docs.redpanda.com/docs/cluster-administration/monitoring/) explicitly tells users not to use rpk for generating Grafana dashboards:
```
* You can use this [sample Prometheus configuration file](https://github.com/prometheus/prometheus/blob/main/documentation/examples/prometheus.yml).
* You can use rpk to configure Prometheus, but do not use rpk to generate a Grafana dashboard for public_metrics.
```

Since we now have support for it, we should guide users towards using rpk.

A section for configuring Grafana should be added to the Monitoring page, like on the [Internal Metrics page](https://docs.redpanda.com/docs/reference/internal-metrics/#configure-grafana-internal-metrics). The example `rpk generate-dashboard` command, should use `public_metrics` instead of `metrics`.

### If the requested update is from customer feedback or a Community slack conversation, provide a link:
https://redpandacommunity.slack.com/archives/C01AJDUT88N/p1665334995212749

### Additional notes
* [PR](https://github.com/redpanda-data/redpanda/pull/6165) that adds suppor for public_metrics to `rpk generate-dashboard`

**Comment by micheleRP** [comment]
@micheleRP also clarify doc per this community post: https://redpandacommunity.slack.com/archives/C01AJDUT88N/p1665253613422389

**Comment by Feediver1** [comment]
@VladLazar Thank you for the ticket. Please note that this item was not part of the 22.3 doc roadmap (until today :-) )

As such, I've added to our roadmap as a content gap. We will get it in asap, but please know that might be after 22.3 GA. If a problem, let's discuss.

https://docs.google.com/spreadsheets/d/1M1UZxe1WYdROKnDrPiWPohwJ25lW-De-MEMQWutH4Kk/edit?usp=sharing

**Comment by VladLazar** [comment]
I think that timeline is fine. We've just got to make sure we don't forget to do it altogether.

**Comment by Feediver1** [comment]
Here is some great material from RPU (@larsenpanda --thanks Chris!)--docs and RPU should be aligned on this guidance.

https://docs.google.com/document/d/1EX76_zEzCrbRmun1pLDx6D3MCn7vi_dREBA7FGsEpz0/edit?usp=sharing

**Comment by rkruze** [comment]
@tmgstevens has also created other dashboards which we should have documented some place or made part of the product @vladoschreiner https://github.com/tmgstevens/redpanda-monitoring

**Comment by mattschumpert** [comment]
@r-vasquez , you said:
```

rpk generate grafana-dashboard --metrics-endpoint localhost:9644/public_metrics will give you the new dashboard, example here:
[https://dev.bamboo.monitoring.dev.vectorized.cloud/grafana/d/6Cx4ZAZVz/rpk-public-metrics-demo-v2?[](https://www.google.com/url?q=https://dev.bamboo.monitoring.dev.vectorized.cloud/grafana/d/6Cx4ZAZVz/rpk-public-metrics-demo-v2?%5B&sa=D&source=docs&ust=1669677888290591&usg=AOvVaw0EYq8ctCcVAuhH0F9OCWE5)…]l&var-node_shard=All&var-aggr_criteria=instance

```
Is this flag still required with 22.3? or is it default?  If not we should definitely document using the --metrics-endpoint flag @micheleRP

**Comment by r-vasquez** [comment]
@mattschumpert Yes, is still required for 22.3.

**Comment by mattschumpert** [comment]
@micheleRP  we need to add this to both 22.2 and 22.3 docs please: https://docs.redpanda.com/docs/platform/cluster-administration/monitoring/

We need to explain how to set the endpoint, e.g.: rpk generate grafana-dashboard --metrics-endpoint localhost:9644/public_metrics

**Comment by Feediver1** [comment]
@tmgstevens Can you please provide @micheleRP a link to the other dashboards that @rkruze mentions here? This is planned for update first week in Jan, so if you could provide by then, that would be great. Thx!

**Comment by Feediver1** [comment]
This material appears in #1059 
Closing as Fixed.
