### ISSUE TITLE
Change admonitions to red on old k8s pages that use Redpanda Operator

### ISSUE THREAD

**Issue by micheleRP** [redpanda-data/documentation#703]
Per Roko: Change the admonition to red on all Redpanda Operator pages that have new Helm v2 pages; e.g., https://docs.redpanda.com/docs/reference/redpanda-operator/kubernetes-qs-minikube/ 

See: 
- https://redpandadata.slack.com/archives/C01LK3UK2K1/p1665414945425199
- https://redpandadata.slack.com/archives/C045VNS4HMG/p1665419599216669

**Comment by Feediver1** [comment]
**Warning** or **Caution**. Docs don't typically use "Danger"--highly frowned upon/not convention.

**Comment by micheleRP** [comment]
> **Warning** or **Caution**. Docs don't typically use "Danger"--highly frowned upon/not convention.

@Feediver1 Are you saying that we should use yellow instead of red? I agree that we don't want to call anything out as "danger", but I think the yellow warning admonition seems even less noticeable than the original blue. We could use that danger admonition to have the red (pink) color jump out and change the title of it to be anything, like Important (just like how we can change the Note title to Notes).

**Comment by Feediver1** [comment]
@micheleRP No. Just that we should not ever use "Danger" (as noted in our Style Guide). If we need to use the red/pink for Warning (which is what Roko requested), I can live with that. If you disagree, then let's decide as a team in our next team mtg.
@Deflaimun Will Docusaurus allow this? In other words, is this customizable? Thx.

**Comment by Deflaimun** [comment]
@Feediver1 Like we talked on the meeting, we can change the behavior of the admonitions.
We can:
1) Remove red (danger) as a possible value
2) Change the title to whatever is more suitable to the text. For example if you tag 
:::important Abc

this creates an admonition with the title Abc

More on that here:
https://docusaurus.io/docs/markdown-features/admonitions

**Comment by Feediver1** [comment]
Let's change/add an admonition for "Important" @Deflaimun

**Comment by Deflaimun** [comment]
Change admonition description from 'info' to 'important'
