### ISSUE TITLE
Cloudv2: VPC Peering for Dedicated Clusters

### ISSUE THREAD

**Issue by AnneLeeperRP** [redpanda-data/documentation#712]
### Describe the Issue

We need documentation to explain how VPC peering works for Dedicated clusters.
I think we need separate topics for AWS and GCP (and any future supported cloud providers). (Need to confirm with @bpraseed )

VPC Peering SME: @birdayz (Johannes)

### If new feature, in which release is it included or expected? 
According to the [Cloud Projects](https://github.com/orgs/redpanda-data/projects/49/views/1?filterQuery=VPC) doc, VPC Peering for Dedicated clusters is expected to be ready on Oct. 28 (limited availability).

### Additional notes
This issue is part of the CloudV2 Documentation "epic" described in #649.

Links to helpful information:

* [Networking PRD](https://docs.google.com/document/d/1upFeIdC2YdXH0ug3-UL3V5t-fGv46YCMiuNda_4vEvE/edit#heading=h.5zvj0etnl8iy)

* Engr. PR that serves as the RFC: [VPC Peering - FMC - One Red Panda Per Network](https://github.com/redpanda-data/cloud/issues/2753)

* Engr. PR for changes to [AWS VPC peering instructions](https://github.com/redpanda-data/cloudv2/issues/2582) in the Redpanda Cloud UI.

* What is VPC Peering ([AWS doc](https://docs.aws.amazon.com/vpc/latest/peering/what-is-vpc-peering.html))

**Comment by Feediver1** [comment]
@AnneLeeperRP Is this issue complete? If so, please close.

**Comment by AnneLeeperRP** [comment]
VPC Peering was included in PR #699 .
