### ISSUE TITLE
Add "Installing Current Version" to the "Install and Upgrade" section

### ISSUE THREAD

**Issue by AnneLeeperRP** [redpanda-data/documentation#713]
### Describe the Issue

**Customer-facing issue impacting their ability to install--Please fix asap.**

See: https://redpandadata.slack.com/archives/C01LK3UK2K1/p1663804930202619

In #help-docs, we got the following feedback from Dhruv, where he describes the confusing organization of the current doc nav tree, and suggestions for adding a new topic:

"I was looking at docs to see what page I should connect to "get community edition" cta. I eventually realized that it should be the 60-sec guides: https://docs.redpanda.com/docs/quickstart/.

But initially, I went to docs home, and clicked on "install and upgrade".. and then the only thing available was "how to install previews"  instead of how to install "current" builds. If 60 sec guides are specific to installation, maybe we should park them under Install? If 60 second guides can be other things in future, then it would be helpful to have a page under install section that just talks about installing regular builds and directs you to pick a 60 second guide of choice.
Not seeing "install current version" on this - https://docs.redpanda.com/docs/install-upgrade/ was confusing."

Dhruv:
Another thing - it would be useful if we could add a setence/ CTA box to request a license key for a 30-day enterprise trial, in our docs in the install guide. 
[@Anne](https://redpandadata.slack.com/team/U037G0S16MN)
.. I can give you a link to our forms, with the appropriate utms if this is agreeable.
I would propose wording like:
"To experience all commercial features of Redpanda Enterprise, including tiered storage, continuous data balancing, and Redpanda Console with SSO/RBAC, please activate your 30-day free trial here.
If you would like to use Redpanda Cloud, please signup for your 30-day free trial here" (edited)

Another thought that came to mind. We see many people on community trying to run performance tests and often they say that they're not seeing expected gains. I was wondering if that happens because many people might be following the quickstarts, and jumping into performance testing, without thinking about tune etc. Would it make sense to insert a sentence that says "if you're looking to evaluate performance, please look into instructions for performance tuning"? (Separately we can work on a benchmarking step by step guide/blog in marketing land to point people to).

Anne:
Interesting point. Could we follow up with the users who comment in the community channel, and see if that's their approach (read the 60-second guides and then try to evaluate performance)? That would tell us if we need to insert a sentence about performance tuning.
Right now, we have two sections under "Performance and storage tuning", which is located under "Deployment":
[Managing Disk Space](https://docs.redpanda.com/docs/deployment/disk-utilization/)
[Optimizing I/O](https://docs.redpanda.com/docs/deployment/io-optimization/)
We don't have a separate landing page for "Performance and storage tuning" (which we need), and we don't link to [Tunable Configuration Properties](https://docs.redpanda.com/docs/reference/tunable-properties/), which we should. We also don't have any guidelines for changing the tunable properties (other than to say "You should only change these properties after collecting sufficient data to warrant a change"). We should also consider relocating "Performance and Storage Tuning" - maybe make it a top-level heading.
Can we meet to discuss the best approach to ensure that customers know how to tune Redpanda to get the best performance results?

### New feature or content gap requests

We need to add a topic under "Install and Upgrade" that describes how to install the latest version of Redpanda. This topic could link to the 60-Second Guides, which contain information on producing and consuming messages in addition to installation instructions.

### Additional notes

**Comment by Feediver1** [comment]
Also see: https://docs.google.com/document/d/1aydKWHK-74nMP2YEz6TCkYKtyRtpQelE5fFVEHqQrEA/edit?usp=sharing
