### ISSUE TITLE
Document new tiered storage data deletion behavior in 22.3

### ISSUE THREAD

**Issue by jcsp** [redpanda-data/documentation#717]
### Describe the Issue

Redpanda didn't used to delete data in S3 when topics were deleted: this is fixed in Redpanda 22.3, along with a new topic property for toggling this deletion behavior, and a safe upgrade path where legacy topics have S3 deletion disabled by default.

### Updates to existing documentation

_Aside: the below details make this sound more complicated than it is: the basic "normal" user behavior here is that when they delete a topic, the topic is deleted: simple.  The complexity all comes from the special handling of legacy topics and the niche option to skip deleting data in S3 when a topic is deleted, which is only needed under special circumstances (e.g. when intervening in an unhealthy cluster and planning on using some external tools to copy+recover from the data in S3, or when using read replicas and deleting the topic from an original cluster while keeping it available for read replicas)._

In previous versions of Redpanda, we wrote data into S3 when using tiered storage, but never deleted it.  When a topic was deleted, the data in S3 related to that topic remained there.  There was no automatic way to remove that data.  Removing it by hand is possible but inadvisable, given the risk of a mistake damaging other topics' data.

In PR https://github.com/redpanda-data/redpanda/pull/6683 there is a new topic configuration property:
- `redpanda.remote.delete` may be set to "true" or "false".  This property appears in output of commands like `rpk topic describe` and may be set with the same `rpk` commands that modify other topic properties (e.g. how we would set `redpanda.remote.write` on a topic.
- `redpanda.remote.delete` is set to `false` on topics that were created with earlier versions of Redpanda.  This preserves the legacy behavior.  This applies only to topics created using old versions of redpanda, not to topics created on clusters after they are upgraded.
- For topics created using Redpanda 22.3 or later, the default value of `redpanda.remote.delete` is `true`.

When a topic is deleted, the topic's data in S3 is also deleted if all of the following are true:
- `redpanda.remote.delete` is true
- Full tiered storage is enabled for the topic (i.e. both `redpanda.remote.read` and `redpanda.remote.write` are true, or their respective cluster-wide defaults are both true).
- The topic is not a read replica topic.

The default behavior for new topics on clusters using tiered storage is intuitive: the `rpk topic delete` command deletes the topic and its data, whether that data is on local storage or in S3.

Legacy topics may be switched to the new behavior by setting `redpanda.remote.delete` to true on each such topic.  After doing this, the topic's data in S3 will be deleted when the topic is deleted in future.

If you wish to delete a topic without removing its data in S3, set `redpanda.remote.delete` to false before deleting the topic.

**Comment by Feediver1** [comment]
@micheleRP Is this all included in the 22.3 tiered storage updates? If so, please close. If not, let's discuss when it will go in. Thx.

**Comment by jcsp** [comment]
@Feediver1 could you bump this one up in the priority a bit?  As we have more 22.3 systems in the field the question of what this property is/does it becomes more of a FAQ

**Comment by micheleRP** [comment]
Cover: 
- https://vectorizedio.atlassian.net/wiki/spaces/CORE/pages/282329096/Changes+to+redpanda.remote.+read+write+topic+properties
- https://vectorizedio.atlassian.net/wiki/spaces/CORE/pages/290521089/Topic+Deletion+Tiered+Storage

SME = John Spray
