### ISSUE TITLE
Update documentation readme

### ISSUE THREAD

**Issue by Deflaimun** [redpanda-data/documentation#721]
### Describe the Issue

The documentation readme was written for the docs team to use it. Now that we have made the repository public it should be revisited to better reflect the new audience. 

It should include style guides, how to contribute, code of conduct (?) and how to run the website locally. 

Examples: 

https://github.com/github/docs

https://github.com/docker/docs

https://github.com/kubernetes/website

**Comment by Feediver1** [comment]
Issues are resolved.
