### ISSUE TITLE
Add heading for Console install under Install and Upgrade in navtree

### ISSUE THREAD

**Issue by Feediver1** [redpanda-data/documentation#728]
### Describe the Issue

This issue is impacting customers - has been brought to the attention of our customer success team (came up during Customer Success sync mtg on Oct 19, 2022).

When installing RP Console, customers look for that guidance under Install and Upgrade at top level of our navtree: https://docs.redpanda.com/docs/install-upgrade/
and there's nothing there. 

Please add a link here to the RP Console Installation docs. We can keep in context of Console heading, but we also need that link under Install and Upgrade.
SO this link needs to be added there: https://docs.redpanda.com/docs/console/installation/
The heading should be "Redpanda Console Installation"

**Comment by Feediver1** [comment]
@Deflaimun Would it be possible to include this in your updates for https://github.com/redpanda-data/documentation/pull/722 ?

**Comment by Deflaimun** [comment]
This has been fixed with #722
