### ISSUE TITLE
Explain that Read Replica clusters should always be upgraded first

### ISSUE THREAD

**Issue by mattschumpert** [redpanda-data/documentation#729]
Our upgrade guide should explain that clusters hosting Read Replica topics must be upgraded at the same time or before origin clusters are upgraded to any different major version. This is due to known and potential future format changes associated with Shadow Indexing which could prevent the Read Replica topics from being readable across major versions.

cc @jcsp

**Comment by mattschumpert** [comment]
@jcsp , seems like Liveramp faced this issue in the current incident, correct?

This should be just a couple of sentences in our upgrade guide and the main Remote Read Replicas topic @Feediver1

**Comment by Feediver1** [comment]
Duplicate. This is covered in https://github.com/redpanda-data/documentation/pull/1548
