### ISSUE TITLE
Add running mirrormaker2 as a service

### ISSUE THREAD

**Issue by larsenpanda** [redpanda-data/documentation#737]
### Describe the Issue

In <a href="https://docs.redpanda.com/docs/data-management/data-migration/">this doc</a> we are running MirrorMaker in such a way that needs to be killed after searching for the pid and we don't point out how to run it in production, which is to run the service as a SystemD unit file.  We should add a section on running it in production in a vm/bare metal environment at least.

### Updates to existing documentation

Here's how to run it as a service.

1. Edit `/etc/systemd/system/multi-user.target.wants/mm2.service` and add the following (NOTE: the home directory and where you are running mm2 from will vary):

```
[Unit]
Description=Mirror Maker 2 service
After=network.target
#StartLimitIntervalSec=0
[Service]
Type=simple
Restart=always
LimitNOFILE=49152
RestartSec=1
User=root
Environment=JAVA_HOME=/usr/lib/jvm/java-11-amazon-corretto
ExecStart=/home/ec2-user/kafka_2.13-3.3.1/bin/connect-mirror-maker.sh /home/ec2-user/mm2.properties

# Output to syslog
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=mm2

[Install]
WantedBy=multi-user.target
```

2. `sudo systemctl daemon-reload`
3. `sudo systemctl start mm2.service`

Also worth noting that you can see progress with `tail -f /var/log/messages | grep mm2` (RH/fedora based) or `tail -f /var/log/syslog | grep mm2` (Debian based).

**Comment by Deflaimun** [comment]
Tagging this issue as blocked since we're missing a review from @larsenpanda at #918
