### ISSUE TITLE
Add instructions for CSI driver to K8s installation instructions

### ISSUE THREAD

**Issue by AnneLeeperRP** [redpanda-data/documentation#738]
### Describe the Issue

EKS version 1.23 requires a CSI driver, which has to be installed manually. We need to add this instruction in the Kubernetes installation docs.

From Redpanda Community #general channel:

"The guide I mentioned in the beginning ([Installing Redpanda on Kubernetes](https://docs.redpanda.com/docs/quickstart/kubernetes-qs-dev/)) includes the cluster creation part but doesn't mention anything about additional (manual?) EBS CSI setup, which the system relies on. This gives a false impression that you should be up and running by simply following the steps mentioned there. Maybe this part should be explicitly mentioned in the guide to avoid confusion. Also, should it be configured right after cluster setup or after Redpanda deployment? Would be nice to have this info there."

More interaction on Slack:

Which EKS version are you using?

- Server Version: v1.23.10-eks-15b7512

So you are using version 1.23. Please try to install CSI.
(NOTE: It appears that just the latest version, 1.23, requires the CSI driver to be installed.)

### Updates to existing documentation

This update applies to https://docs.redpanda.com/docs/quickstart/kubernetes-qs-dev/.

### If the requested update is from customer feedback or a Community slack conversation, provide a link:

Link to slack convo: https://redpandacommunity.slack.com/archives/C01B3QBLUTT/p1666287356651039

### Additional notes

Links to AWS docs (provided by community user):
* [Amazon EBS CSI Driver](https://docs.aws.amazon.com/eks/latest/userguide/ebs-csi.html)
* [Amazon EKS Kubernetes versions](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html)

SME: Start with @joejulian

**Comment by joejulian** [comment]
_**WARNING: THIS HASN'T BEEN TESTED YET**_
I just wanted to get this somewhere so it won't get lost.

Append to the Amazon EKS _Tab_
---
Create the IAM role needed for the Amazon Elastic Block Store (EBS) Cluster Storage Interface (CSI):

```
eksctl create iamserviceaccount \
  --name ebs-csi-controller-sa \
  --namespace kube-system \
  --cluster redpanda \
  --attach-policy-arn arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy \
  --approve \
  --role-only \
  --role-name AmazonEKS_EBS_CSI_DriverRole
```
Add the EBS CSI add-on:

In the following command, `$AWS_ACCOUNT_ID` is your Amazon account id. You can retrieve that from the aws cli by running `aws sts get-caller-identity`.

```
AWS_ACCOUNT_ID=111122223333
eksctl create addon \
  --name aws-ebs-csi-driver \
  --cluster redpanda \
  --service-account-role-arn arn:aws:iam::${AWS_ACCOUNT_ID}:role/AmazonEKS_EBS_CSI_DriverRole \
  --force
```

**Comment by JakeSCahill** [comment]
Notified the user of the updates on Slack.
