### ISSUE TITLE
Add missing infrastructure metrics

### ISSUE THREAD

**Issue by VladLazar** [redpanda-data/documentation#752]
### Describe the Issue
`redpanda_cpu_busy_seconds_total` and `redpanda_runtime_seconds_total` metrics are missing from the table [here](https://docs.redpanda.com/docs/cluster-administration/monitoring/#infrastructure-level-metrics).

### Updates to existing documentation
We should add `redpanda_cpu_busy_seconds_total` and `redpanda_runtime_seconds_total` [here](https://docs.redpanda.com/docs/cluster-administration/monitoring/#infrastructure-level-metrics).

redpanda_cpu_busy_seconds_total:
Definition: Total CPU busy time in seconds
Labels: none
Type: gauge

redpanda_uptime_seconds_total:
Definition: Total CPU busy time in seconds
Labels: none
Type: gauge

cc @larsenpanda

**Comment by shorgi** [comment]
@VladLazar - shouldn't `redpanda_uptime_seconds_total` have a different description than `redpanda_cpu_busy_seconds_total`?   From https://github.com/redpanda-data/redpanda/commit/be504a9cc80a811c502032fcb662485a585ede94, I'm guessing it should be based on the description, "Accumulated runtime of task queue associated with this scheduling group."

**Comment by VladLazar** [comment]
@shorgi - Sigh.. You're right. Copy pasted them by mistake.

**Comment by shorgi** [comment]
@VladLazar thanks for confirming, will fix it in #975 .
