### ISSUE TITLE
Reading feedback on Core > Cluster Administration > Configuration page

### ISSUE THREAD

**Issue by weeco** [redpanda-data/documentation#760]
After reading this page: https://docs.redpanda.com/docs/cluster-administration/configuration/ I have two remarks:

1. Text mentions "Kafka frontend settings". I'm unsure what is meant by Kafka frontend settings?
2. Examples for unique node settings - I think the `example is the kafka_api listener IP address. ` is not a good example, because in fact this is likely often set to the same socket `127.0.0.1:9092` for all nodes. Instead you probably meant the `advertised_kafka_api` config.

**Comment by micheleRP** [comment]
Closing, as this page was updated and these items are no longer included: https://docs.redpanda.com/docs/manage/configuration/
