### ISSUE TITLE
Reference cluster config template is not comprehensive

### ISSUE THREAD

**Issue by patrickangeles** [redpanda-data/documentation#767]
### Describe the Issue

Some properties are missing from the [cluster configuration properties reference page] (https://docs.redpanda.com/docs/platform/reference/cluster-properties/)

For example, these configs from [continuous data balancing](https://docs.redpanda.com/docs/platform/cluster-administration/continuous-data-balancing/) are missing.

The reference page should have all configuration properties, ideally with a link back to the feature documentation page (if one is available) that has further details.

**Comment by shorgi** [comment]
Resolved by #1203
