### ISSUE TITLE
4Q 22.4 Redpanda for Kubernetes content 

### ISSUE THREAD

**Issue by Feediver1** [redpanda-data/documentation#783]
### Describe the Issue

We need a standalone Redpanda for Kubernetes guide (for a model, take a look at https://docs.confluent.io/operator/current/overview.html). 

Kubernetes is a supported platform for Redpanda. The material is currently spread out in various topics, but there are a myriad of content gaps. This ticket includes all the tickets filed to date as well as links to helpful docs. 
SMEs: @joejulian @jrkinley  

Writer should also spend some time scrolling through/researching the following Slack channels for k8s questions/material:
- Redpanda Community Slack channels (#redpanda, #console, #general)
- #kubernetes

Other helpful resources:
[Redpanda Benchmark on Kubernetes](https://redpandadata.slack.com/archives/C01H6JRQX1S/p1667463476751939)

This ticket serves as the epic.
Check:
- https://github.com/redpanda-data/documentation/issues/437 (unclear if this still applies; vet with @joejulian )

**Comment by Feediver1** [comment]
For a framework/to get started, see https://docs.google.com/document/d/1eaGmZB3VVybkNapnFMML1ztihukCd-3bUnbXzVUQDdo/edit?usp=sharing

Another SME is @tmgstevens

**Comment by Feediver1** [comment]
There are many posts in Redpanda Community requesting guidance on K8S--cull through the channels there and search for K8S--this should provide good context/feedback regarding our customers' struggle to get comprehensive guidance from docs for this platform. https://redpandacommunity.slack.com/archives/C01AJDUT88N/p1668163378353569

**Comment by JakeSCahill** [comment]
**Status update:** I've been researching the topic of Redpanda on K8 using helm for the past couple of days. I'm now aggregating all my K8 research so far into a document. When it's ready, I'll schedule a call with Roko to review it and agree on topics to prioritize for Q4.

**Comment by JakeSCahill** [comment]
All the related PRs are merged
