### ISSUE TITLE
Add note - If decommissioning a node, do not put it into maintenance mode

### ISSUE THREAD

**Issue by Feediver1** [redpanda-data/documentation#791]
### Describe the Issue

Issue came up for a user in Community Slack:
https://redpandacommunity.slack.com/archives/C01AJDUT88N/p1667848435753559

Per @dotnwat "If you're going to decommission a node, don't put it into maintenance mode" - add this as a note in https://docs.redpanda.com/docs/platform/cluster-administration/node-management/

**Comment by AnneLeeperRP** [comment]
Closing this as a dup of issue #522 .
