### ISSUE TITLE
Add what happens to Enterprise features once license expires

### ISSUE THREAD

**Issue by daisukebe** [redpanda-data/documentation#793]
### Describe the Issue

It's unclear to customers on what happens to the enterprise features once the license expires. 

### Updates to existing documentation

Let's document it in https://docs.redpanda.com/docs/platform/introduction/licenses/

**Comment by Feediver1** [comment]
@mattschumpert Can you provide this information to @micheleRP ? When will we start enforcing RP Enterprise licenses? The user experience wrt licensing is inconsistent between our existing enterprise license features and RP Console. This inconsistency can lead to a confusing user experience. Minimally, docs should provide clear guidance on what users can expect if/when their license(s) have expired. Thx.

**Comment by Feediver1** [comment]
@daisukebe Looks like we are not going to roll out any type of enforcement (outside of RP Console) until 3Q2023: https://redpandadata.slack.com/archives/C02FSLH3ZS9/p1674487599405919

**Comment by emaxerrno** [comment]
strict enforcement ETA q3/q4-FY24. atm on the core it just prints a message. 

we have to err on the side of safety since redpanda not starting means outages for people. 

eventually this will converge like console.

**Comment by Feediver1** [comment]
@micheleRP For now, let's be transparent with customers and simply share the message they will see. 
@daisukebe I suspect when Enterprise license enforcement is implemented (see @emaxerrno 's comment above), docs will get a new ticket for this in the release in which it is included.

**Comment by mattschumpert** [comment]
@graphcareful knows the exact message we'll show in logs

**Comment by daisukebe** [comment]
Thanks @Feediver1. 

@micheleRP, here's the exact message we show in logs

https://github.com/redpanda-data/redpanda/blob/v22.3.11/src/v/cluster/feature_manager.cc#L202-L206
```
Looks like you’ve enabled a Redpanda Enterprise feature(s) without a valid license. Please enter an active Redpanda license key (e.g. rpk cluster license set <key>). If you don’t have one, please request a new/trial license at https://redpanda.com/license-request
```
