### ISSUE TITLE
Rename 60-second guide tile on doc home page

### ISSUE THREAD

**Issue by Feediver1** [redpanda-data/documentation#795]
### Describe the Issue

Notion of 60-second guide is already gone (takes way longer...).

Content has been moved to Install section. No Quickstarts...Rename the tile to "Get Started with Redpanda"
https://docs.redpanda.com/docs/home/platform/

**Comment by Feediver1** [comment]
@Deflaimun Let's shoot for end of this week (Nov 11) on this one--it's a confusing user experience to see this tile and then to not see it mentioned in the navtree. Thanks.

**Comment by Deflaimun** [comment]
Shoiuld we keep the description "Try out Redpanda." ?
