### ISSUE TITLE
Security Guide for Cloud

### ISSUE THREAD

**Issue by patrickangeles** [redpanda-data/documentation#796]
We need a guide for enabling / configuring / using security features (AuthZ, AuthN, encryption, etc.) in the Cloud. Separately, we also want overlapping material that discusses the security architecture of v2 targeted for infosec reviews. This includes BYOC Security content.

**Comment by AnneLeeperRP** [comment]
@bpraseed and @c4milo are working on a white paper - targeted for Q4.
Docs can follow in 2023Q1.

**Comment by Feediver1** [comment]
Start work on this topic and leverage white paper by @c4milo [Redpanda Cloud Security and Compliance](https://docs.google.com/document/d/11MvgNdQF0ebY61NmrzYfkzW9GQqWi0j-rLzojCuSM7k/edit?usp=sharing)
Still need to collect content/info on:
- Redpanda Cloud Cluster Release Certification
Access Control:
- Security Governance Model	
- AuthN
- Role and Attribute Based Access Controls 
- Zero Trust Access
@bpraseed Does any of the missing info exist anywhere?

**Comment by bpraseed** [comment]
@Feediver1 - can we use what we have as Eng fills the rest. We could use what we share with customers today. (Attached)
https://docs.google.com/document/d/12JDlYAaXExAEsoWnp7s_1c6JXAWLZWr5Fj-IZEca2GA/edit
