### ISSUE TITLE
1Q 23.1  Document Tiered Storage support for Azure 

### ISSUE THREAD

**Issue by Feediver1** [redpanda-data/documentation#799]
### Describe the Issue

Document how self-hosted customers can deploy Redpanda in Azure using tiered storage. 

[RFC Draft](https://docs.google.com/document/d/1RikSuW07TuSr78BMJGJG9HHXOh5XeQ6xP_Ku0gN-JPU)
Redpanda Slack channel: #azure-tiered-storage https://redpandadata.slack.com/archives/C0407G6JBFU

### Who is this for and what problem does it solve?

For Azure cloud customers who want to use shadow indexing. The plan is to mitigate that currently only s3 is supported, with a minio gateway, but as the minio project has now removed that functionality, this is not longer tenable. So Redpanda plans to provide (natively) azure storage support.

### What does success look like for the customer?

They are able to use azure blob storage for shadow indexing - this is what needs to be documented: 
- Prerequisites?
- Configuration steps
- Examples/Use cases (coordinate with PM and customer success what they should be)

### Questions for PM/Eng

- How do users authenticate with Azure blob storage in their environment? Using Managed Identities for VMs, plaintext secrets in Key Vault, something else?

- On the AWS side we have IAM roles for this, so looking to work out what the preferred Azure equivalent is.

**SMEs**:
https://github.com/michaelandrepearce
@jcsp (Engineering)
@Lazin 
@patrickangeles (Customer Success)
@mattschumpert (PM)

**Comment by Feediver1** [comment]
Engineering Epic: https://github.com/redpanda-data/core-internal/issues/127

**Comment by micheleRP** [comment]
Resolved with #1057 and #1257
