### ISSUE TITLE
23.1: Document cluster-wide rate limits

### ISSUE THREAD

**Issue by Feediver1** [redpanda-data/documentation#807]
### Describe the Issue

**Engineering Issue**
Currently, most of our rate limits are shard local. This is sufficient for "protective" rate limits that control a workload's impact on shard-local resources, but insufficient for:

- Protecting shared node-wide resources, such as disk
- Exposing "official" rate limits to users for a whole cluster, such that the rate a user experiences is independent of how their activity is spread across cores, and independent of how we up/downscale the cluster.
**Engineering Solution**
The solution will look like a series of named token buckets (for e.g. bytes per second, events per second), and RPC mechanisms for nodes to steal tokens from each other + also steal shares of token generation so that in steady state they do not need to do many RPCs.

See https://github.com/redpanda-data/core-internal/issues/133

**Comment by Feediver1** [comment]
@mattschumpert Please update this ticket to include more context for the writer, and to also suggest use cases that should be documented.

@jcsp 
Are there any prerequisites here? Caveats/gotchas? Troubleshooting info? 
Any details wrt implementation are appreciated! Thx.

**Comment by Feediver1** [comment]
Eng Epic: https://github.com/redpanda-data/core-internal/issues/133

**Comment by mattschumpert** [comment]
@Feediver1  we won't know the exact shape of this feature until its build later this quarter, certainly not troubleshooting/gotcha level info.

**Comment by Feediver1** [comment]
Marking blocked until there is sufficient guidance to move forward with this doc in Q4.

**Comment by Feediver1** [comment]
@mattschumpert @piyushredpanda Please be aware that all docs for 23.1 must be complete by 02/08/2023. This is not the date on which @micheleRP gets raw data, nor the date on which reviews begin - it's the date Michele must have the content written, reviewed, revised, and merged. Anything that comes after this date will likely be pushed into the subsequent release. Thx.

**Comment by mattschumpert** [comment]
@micheleRP  the person to work with here is the assignee of the linked ticket (@dlex ).  These are just a few new cluster configuration properties admins can configure as guardrails.

**Comment by dlex** [comment]
@micheleRP [Here](https://docs.google.com/document/d/1AbOa27Cd6fxNyGdYsOiwTYK68AwDEIcf9IK0o2VSqYc/edit?usp=sharing) is the RFC. It is lengthy and elaborate, please check out the Summary section there (the Details section mostly discusses implementation details and alternatives). The ticket delivered in Q1 #7855 only covers half of the RFC.

**Comment by Feediver1** [comment]
@dlex to help expedite the updates, can you please list the properties that are new or should be updated? 29-page RFC to a few property updates seems like an inefficient way for the writer to get the necessary info. Is there a eng PR already open too? That would help/be great.

**Comment by Feediver1** [comment]
@shorgi Given that this is for property updates, reassigning to you.

**Comment by dlex** [comment]
> can you please list the properties that are new or should be updated

Please check the "UX Changes" section in the description of these PRs:
* https://github.com/redpanda-data/redpanda/pull/8023
* https://github.com/redpanda-data/redpanda/pull/8335

**Comment by shorgi** [comment]
Resolved for 23.1 by #1140 and #1192
