### ISSUE TITLE
Docker quickstart examples don't work

### ISSUE THREAD

**Issue by patrickangeles** [redpanda-data/documentation#817]
The examples in the following link don't work. For one thing, it seems that a line was added without a proper line continuation character `\` which causes the command to be broken up:

```
--overprovisioned \
--set redpanda.empty_seed_starts_cluster=false
--seeds "redpanda-1:33145" \
```

https://docs.redpanda.com/docs/platform/quickstart/quick-start-docker/

**Comment by patrickangeles** [comment]
Also, this is referencing an old version:
```
    image: docker.redpanda.com/vectorized/redpanda:v21.11.15
```

**Comment by micheleRP** [comment]
reopening to address new comments: https://github.com/redpanda-data/documentation/pull/820
