### ISSUE TITLE
Clarify mTLS documentation

### ISSUE THREAD

**Issue by micheleRP** [redpanda-data/documentation#823]
### Describe the Issue

feedback on the lounge session that the mTLS docs were hard to use and they were not able to get it working based upon it. See
https://redpandadata.slack.com/archives/C01LK3UK2K1/p1668531596356479
https://redpandacommunity.slack.com/archives/C048589SBEZ/p1668529728609809

### Updates to existing documentation

Here's where our doc covers mTLS. Joe's working on the K8s page (see [here](https://redpandacommunity.slack.com/archives/C048589SBEZ/p1668529728609809)), so please look at the encryption & authentication pages first!
[Configuring Encryption](https://docs.redpanda.com/docs/platform/security/encryption/#mtls)
[Configuring Authentication](https://docs.redpanda.com/docs/platform/security/authentication/)
[Configuring mTLS on Kubernetes](https://docs.redpanda.com/docs/platform/reference/redpanda-operator/kubernetes-mtls/) (reference, with Redpanda Operator)

**Comment by micheleRP** [comment]
SMEs = Patrick Angeles, Denis Coady

**Comment by dcoded** [comment]
> The generate certs example doesn't work. (I tried on MacOS, it didn't do anything.)

I can also reproduce the issue.

> Also, it should probably be hosted in an official Redpanda GitHub repo, not an employee repo.

Agreed. This should be put under the Redpanda organization. I think a gist is fine, but needs to be pulled under the control of Redpanda.

> We should describe what the script does (generates and download scripts)... might be better to also document how to do this manually?

+1 from me on this. I personally never get "warm and fuzzies" from piping a script on the internet into my bash shell. It's convenient and I think we should keep it, but having a walkthrough as well would be better.

Additionally, I think that in addition to fixing the script it may be worthwhile to show not only create self-signed certificates but generate certificate signing requests (CSRs) in case they wish to sign with an internal corporate certificate authority.

I've taken a stab at correcting the code and adding some comments that may help with a walkthrough. What do you think @patrickangeles?


## Creating Certificate Signing Requests

### Create node certificate configuration

**TODO:** We may need to mention in this config file that for production usage they will need to update the distinguished_name and alt_names sections.

```
# node.cnf

[ req ]
prompt = no
distinguished_name = distinguished_name
req_extensions     = extensions

[ distinguished_name ]
organizationName = Vectorized

[ extensions ]
subjectAltName = @alt_names

[ alt_names ]
DNS.1 = localhost
DNS.2 = redpanda
DNS.3 = console
DNS.4 = connect
IP.1  = 127.0.0.1

```

```bash
# Generate a 2048-bit RSA private key for nodes.
#
# Outputs:
#   -out node.key   The public key certificate of the certificate authority.
#
openssl genrsa -out node.key 2048

# Create a public certificate signing request (CSR) for the nodes.
#
# Inputs:
#   -new            New request
#   -config ca.cnf  Configuration file to use when generating certificates (created above).
#   -key ca.key     Private key of the node (created above).
#
# Outputs:
#   -out node.crt   The public key certificate of the certificate authority.
#
openssl req -new -config node.cnf -key node.key -out node.csr
```

**TODO:** At this point we should ensure users understand that these CSRs need to be signed with the following extensions:
```
keyUsage         = critical,digitalSignature,keyEncipherment
extendedKeyUsage = serverAuth,clientAuth
```

## Creating a Local Certificate Authority for Self-signed Certificates (Optional)

### Create the certificate authority configuration file (ca.cnf)
```
# ca.cnf
# 
# (optional) edit the distinguished_name section below with your own organization details.

[ ca ]
default_ca = CA_default

[ CA_default ]
default_days    = 365
database        = index.txt
serial          = serial.txt
default_md      = sha256
copy_extensions = copy
unique_subject  = no

[ req ]
prompt = no
distinguished_name = distinguished_name
x509_extensions    = extensions

[ distinguished_name ]
organizationName = Vectorized
commonName       = Vectorized CA

[ extensions ]
keyUsage         = critical,digitalSignature,nonRepudiation,keyEncipherment,keyCertSign
basicConstraints = critical,CA:true,pathlen:1

# Common policy for nodes and users.
[ signing_policy ]
organizationName = supplied
commonName       = optional

# Used to sign node certificates.
[ ext_node ]
keyUsage         = critical,digitalSignature,keyEncipherment
extendedKeyUsage = serverAuth,clientAuth

# Used to sign client certificates.
[ ext_client ]
keyUsage         = critical,digitalSignature,keyEncipherment
extendedKeyUsage = clientAuth
```

### Generate certificate authority private key and public certificate
```bash
# Re(create) the required files denoted in ca.cnf
rm -f index.txt serial.txt
touch index.txt
echo '01' > serial.txt

# Create a certificate authority key to self-sign certificates.
openssl genrsa -out ca.key 2048
chmod 400 ca.key

# Create a public certificate for the certificate authority.
#
# Inputs:
#   -new            New request
#   -x509           Create an X.509 cert instead of a certificate signing request (CSR).
#   -config ca.cnf  Configuration file to use when generating certificates (created above).
#   -key ca.key     Private key of the certificate authority (created above).
#   -days 365       Number of days signed certificates will be valid for.
#   -batch          In batch mode certs will be certified automatically. No questions asked.
#
# Outputs:
#   -out ca.crt     The public key certificate of the certificate authority.
#
openssl req -new -x509 -config ca.cnf -key ca.key -days 365 -batch -out ca.crt
```

### Sign Certificates
```bash
# Sign and generate X.509 certificate for Redpanda node.
#
# Inputs:
#   -req                 Input is a certificate request. Sign and output.
#   -signkey ca.key      Private key of the certificate authority (created above).
#   -days 365            Number of days signed certificates will be valid for.
#   -extfile ca.cnf      Configuration file for certificate authority.
#   -extensions ext_node Section in ca.cnf to use when applying extensions.
#   -in node.csr         Node certificate signing request (CSR generated above).
# Outputs:
#   -out node.crt        The signed public key certificate for the node.
#
openssl x509 -req -signkey ca.key -days 365 -extfile ca.cnf -extensions ext_node -in node.csr -out node.crt
```

**Comment by micheleRP** [comment]
Specific links for docs:
- https://redpandacommunity.slack.com/archives/C048589SBEZ/p1668537215958149?thread_ts=1668529728.609809&cid=C048589SBEZ
- https://redpandacommunity.slack.com/archives/C048589SBEZ/p1669061663179749?thread_ts=1668529728.609809&cid=C048589SBEZ
