### ISSUE TITLE
Need to specify the required CLUSTER/kafka-cluster acls for Console user

### ISSUE THREAD

**Issue by jason-da-redpanda** [redpanda-data/documentation#834]
### Describe the Issue
Need to specify the required CLUSTER/kafka-cluster acls for the Console user
e.g is it the full set of CLUSTER Operations required , or partial 

### Updates to existing documentation
https://docs.redpanda.com/docs/platform/quickstart/console-installation/

### New feature or content gap requests
It's missing info.

### If the requested update is from customer feedback or a Community slack conversation, provide a link:
This came from a customer issue(slack)

**Comment by Feediver1** [comment]
@jason-da-redpanda Could you share the link to the support incident page in ZenDesk? Thx.

**Comment by JakeSCahill** [comment]
This page no longer exists. Closing for now, we can reopen if needed.
