### ISSUE TITLE
23.1: Document network and storage self-test

### ISSUE THREAD

**Issue by Feediver1** [redpanda-data/documentation#840]
### Describe the Issue

A new debugging tool to be contained and orchestrated by redpanda is being proposed for and loosely named the Redpanda Self-Test. The Self-Test is intended to be run by support or the client themselves to test whether the infrastructure beneath the redpanda installation is working properly. The Self-Test will achieve this by performing some actions like disk writes, network requests etc. on all nodes.

RFC: https://docs.google.com/document/d/1UBc9CcD-mKkVOtPbO5G_t7UuU2GUIP3I0nnCPTDFpEY/edit?usp=sharing
SMEs: @graphcareful @jcsp 
PR: https://github.com/redpanda-data/redpanda/pull/8398

**Comment by Feediver1** [comment]
@graphcareful Is this feature going into 23.1? Please advise.

**Comment by graphcareful** [comment]
> @graphcareful Is this feature going into 23.1? Please advise.

Yes

**Comment by Feediver1** [comment]
@graphcareful @mattschumpert Docs needs specific guidance on what is user-facing:
- Prerequisites
- Install info (if applicable)
- Config (if applicable)
- Vary by user platform?
- Steps for running
- Any troubleshooting info?
- Any other info users need to run the tool?

The RFC does not clearly indicate what made it into the feature, nor does it indicate how users interface with this tool. Is it currently available in the nightly repo? Docs needs specific guidance on how to set up and use this tool Thx.

**Comment by Feediver1** [comment]
Reassigned to you @shorgi as this is a performance monitoring-related issue.

**Comment by mattschumpert** [comment]
From the RFC:

> What is being proposed
A new mode for testing the cluster infrastructure to affirm that it is in a reliable state or not. The test will be invoked through the admin API to be invoked by tools like rpk or console, to which they will receive a json response with the reports from each individual node. The report will detail the findings which will include insights into things like network status, disk latency, etc. the extent of which will be described below.

Overview of supported use cases
The use cases for such a feature all pertain to testing and debugging. Mainly this tool should be used as a first or secondary debugging step, or when previous debugging efforts have revealed some doubts about the underlying infrastructure.
>

For more details, I suggest the doc writer meet with the SME 1:1 to kick this off.
