### ISSUE TITLE
engine: Provide more context in internal search results

### ISSUE THREAD

**Issue by JakeSCahill** [redpanda-data/documentation#855]
### Describe the Issue

When you enter a query into our search box, the results don't differentiate between Cloud and Platform. It would be useful to configure Algolia to display the product to which the search result applies.

The highlighted results are for Cloud, but the label is 'Documentation':

![2022-11-24_18-18-01](https://user-images.githubusercontent.com/45230295/203846885-c7774d48-3a8b-47ad-8e30-0abbed7f2ce7.png)

**Comment by Feediver1** [comment]
Now that we have removed the cloud folder and placed that content all back under Deploy, is this even possible @Deflaimun ? If not, we should close.

**Comment by Feediver1** [comment]
Will assign priority if/when we determine whether or not this is do-able.

**Comment by Deflaimun** [comment]
Its currently not possible to create this differentiation in our docs. Also, now that we have a different implementation for cloud/platform this issue doesn't apply anymore.
