### ISSUE TITLE
k8s quickstart for performance - GKE and AWS guides

### ISSUE THREAD

**Issue by coral-waters** [redpanda-data/documentation#86]
Long term solution - Add extended guides for GKE, AWS

https://vectorized.atlassian.net/browse/VD-5

Acceptance Criteria

This guide must address situations where the user face aio-max-nr error at startup. More info on the comment down below

**Comment by JakeSCahill** [comment]
Status: We aren't working on issues for Operator at the moment. This issue will be fixed when the new Redpanda Operator is released.

**Comment by JakeSCahill** [comment]
The guide currently has this note, which covers this issue:

> In these steps, the YAML file you use to install Redpanda sets developerMode: true. If you choose to set developerMode: false, run rpk redpanda tune all directly on the host before you create a Redpanda cluster. This command sets tuning parameters for optimal configuration. For more information, see [Set Redpanda production mode](https://docs.redpanda.com/docs/deploy/deployment-option/self-hosted/manual/production/production-deployment/#Step-2-Set-Redpanda-production-mode). If rpk is not available, verify that fs.aio-max-nr is set to 1048576 or greater. You can set fs.aio-max-nr by running sysctl -w fs.aio-max-nr=1048576.

https://docs.redpanda.com/docs/reference/redpanda-operator/kubernetes-qs-local-access/
