### ISSUE TITLE
document all flags in quickstart

### ISSUE THREAD

**Issue by micheleRP** [redpanda-data/documentation#871]
### Describe the Issue

Add developer-focused doc around flags. See community slack: https://redpandacommunity.slack.com/archives/C01AJDUT88N/p1668929030743389

e.g., The --smp N flag tells Seastar (the framework Redpanda uses under the hood) to use N number of cores on the system.

**Comment by JakeSCahill** [comment]
I can take this as part of the quickstart epic.
