### ISSUE TITLE
Add Configure Topics content

### ISSUE THREAD

**Issue by Feediver1** [redpanda-data/documentation#887]
### Describe the Issue

Despite being a fundamental aspect of RP/Kafka, we do not fully document how to create and configure topics. For a model, see https://docs.confluent.io/operator/current/co-manage-topics.html.

Minimally, this content should describe how to create, update, and delete topics using rpk or APIs. Be sure to include any prerequisites, caveats/gotchas. ALways link to the specific rpk commands in rpk ref.

**Comment by Feediver1** [comment]
See: https://redpandadata.slack.com/archives/C03KAHQ776C/p1669880933890409

**Comment by Feediver1** [comment]
@AnneLeeperRP Be sure to also include compacted and non-compacted topic description/guidance.

**Comment by Feediver1** [comment]
@AnneLeeperRP Can you please provide a status update/when to expect the PR? Thx.

**Comment by AnneLeeperRP** [comment]
@Feediver1 
I created a google doc, "[All about Topics](https://docs.google.com/document/d/1qmzHU4Lx7uA5_4qTo7i9aQQvZzlM53xIHAgX-2HroVQ/edit#heading=h.3g2f7jqwbnqd)", which I shared with you. This document has a rough outline based on the recommendations from @jrkinley in response to my request in the slack channel you linked above. I noted where I need help from James to fill out the information.

**Comment by AnneLeeperRP** [comment]
Content (from issue #1373) that will go in "Configure Topics":

- Creating a topic
- Producing records to a topic
- Getting a description of a topic
- Deleting a topic
- Consuming records from a topic (use rpk topic consume -g <group-name> if a group is created)
- -Creating consumer groups (rpk group)
- Getting a description of a consumer group
- Deleting a consumer group

**Comment by AnneLeeperRP** [comment]
This request to add info to the output of `rpk topic describe` will affect the example in "Listing topic configuration settings":
https://redpandadata.slack.com/archives/C04LYNJQUGN/p1679065536339599
