### ISSUE TITLE
Create a page to explain what is Redpanda's versioning scheme

### ISSUE THREAD

**Issue by Deflaimun** [redpanda-data/documentation#888]
### Describe the Issue

During the execution of this [PR](https://github.com/redpanda-data/documentation/pull/859) we mention that users should only upgrade one major version at a time. But we never clearly inform what constitutes a major version for us. 

So, ideally we should create a page to clearly explain to our users what is our versioning scheme. Essentially this page should have:

- Why do we number our versions like that.
- What do we define as a major version release.
- What is a minor version.
- Why we don't have specific docs for minor versions.
- And any other subjects relative to versions, like for example, if we respect common versioning schemes like [SemVer](https://semver.org/)

### New feature or content gap requests

- Gap

**Comment by Feediver1** [comment]
Do you want to add this to the docs @mattschumpert ?

**Comment by mattschumpert** [comment]
Source content here: https://vectorizedio.atlassian.net/wiki/spaces/product/pages/106397701/Redpanda+Releases+Versioning+Support#Versioning

**Comment by mattschumpert** [comment]
@rkruze  is raising the priority of this.

Besides explaining the scheme (content on wiki) and the one major version at a time rule, we make a soft recommendation to

-  upgrade to the latest patch release of a major version before upgrading major versions.  (e.g. go to 22.2.latest before going to 22.3.x)
-  also to go to the latest patch release of the target major release.
