### ISSUE TITLE
Revert RP Cloud landing page - place Cloud content under Deploy

### ISSUE THREAD

**Issue by Feediver1** [redpanda-data/documentation#889]
### Describe the Issue

Guidance is that moving Cloud into a separate repo/landing page is premature. This issue is to get that content moved under the Deployment heading in the navtree, and remove the Cloud landing page/repo.

For details about this placement, refer to the [RP Doc landing page restructure plan](https://docs.google.com/document/d/1ky1Sumz_cywclV9L8dYIkCNrqm-ae2o8UW65QNfwNQU/edit?usp=sharing).

**Comment by Deflaimun** [comment]
The work on this issue has been completed, however, for a better user experience, we're holding off this publication, since we're making more changes to the landing page.

This has been merged to landing-page-overhaul branch.
