### ISSUE TITLE
Tunable properties page

### ISSUE THREAD

**Issue by Deflaimun** [redpanda-data/documentation#893]
### Describe the Issue

The tunable properties page have a lot of problems regarding inconsistency. For example, we don't mention the units of every value that we use there. Sometimes we use values in seconds, other times the values are in microseconds. 

This page should be revisited so that all boxes that require a unit are properly declared. 

### Updates to existing documentation

https://docs.redpanda.com/docs/platform/reference/tunable-properties/

**Comment by shorgi** [comment]
I underestimated the scope of this issue, first because replacing the table with headings required more manual effort, and second because more properties than expected are documented incorrectly, thus requiring research and rewrites.

Increasing estimate from 3 to 8. 

cc @Feediver1 @h-garcia
