### ISSUE TITLE
Typo when requesting AWS CLI to be available

### ISSUE THREAD

**Issue by piyushredpanda** [redpanda-data/documentation#902]
On https://docs.redpanda.com/docs/platform/reference/redpanda-operator/kubernetes-qs-cloud/#amazon-eks-prerequisites page, we have a typo. 

> Install AWK CLI. See the [AWS documentation](https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html).

It is AWS not AWK.

**Comment by piyushredpanda** [comment]
Sorry this could have been a quick PR on my end, but I don't know if there are other places where this typo exists, so wanted to flag here.

**Comment by Feediver1** [comment]
Fixed the content in the source file in dev. Typo gone. Closing.
