### ISSUE TITLE
Doc for `max_concurrent_producer_ids` RP setting

### ISSUE THREAD

**Issue by VadimPlh** [redpanda-data/documentation#906]
### Describe the Issue
In redpanda we do not have mechanism to clear information for old transaction/idempotent producers
So during the time redpanda can store to much data about it and got memory overflow.
To fix this we introduce new settings to limit number of saved producers sessions.

If redpanda notice overflow it will delete old session(by `least recently used` cache police), so after clearing deleted sessions will be invalidated.

### If new feature, in which release is it included or expected? 
Included in v22.3.5 release

### Additional notes

PR: https://github.com/redpanda-data/redpanda/pull/7057
Issue: https://github.com/redpanda-data/redpanda/issues/5321

**Comment by shorgi** [comment]
@VadimPlh - `max_concurrent_producer_ids` was documented as part of https://github.com/redpanda-data/documentation/pull/963.

Does this doc look good to you: https://docs.redpanda.com/docs/reference/tunable-properties/#max_concurrent_producer_ids

**Comment by VadimPlh** [comment]
> @VadimPlh - `max_concurrent_producer_ids` was documented as part of #963.
> 
> Does this doc look good to you: https://docs.redpanda.com/docs/reference/tunable-properties/#max_concurrent_producer_ids

Yes, it looks good! Thanks!

**Comment by shorgi** [comment]
Closing, thanks for confirming @VadimPlh
