### ISSUE TITLE
Document supported hardware architectures

### ISSUE THREAD

**Issue by jcsp** [redpanda-data/documentation#927]
@zamazan4ik commented on [Sat Jun 25 2022](https://github.com/redpanda-data/redpanda/issues/5234)

### Who is this for and what problem do they have today?

For architects, developers and system administrators.

### What would you like fixed in or added to the documentation?

Could you please put the information about supported architectures to the documentation please? E.e. about supported architectures for different operating systems, some specific requirements to the supported instructions, if you have any (e.g. maybe AVX is required - I do not know).

### Is this a new feature or a gap in the documentation?

Gap in the documentation.

**Comment by micheleRP** [comment]
See 
- https://redpandadata.slack.com/archives/C01ND4SVB6Z/p1678489686013079 
- https://vectorizedio.atlassian.net/wiki/spaces/product/pages/178454531/Redpanda+Hardware+and+Software+Requirements

**Comment by mattschumpert** [comment]
@jcsp what's AVX?

**Comment by micheleRP** [comment]
> @jcsp what's AVX?

Not sure where it's getting this info, but if you ask chatGPT for step by step instructions for installing Redpanda Data, it says: 
- Make sure your system meets the minimum requirements. Redpanda Data requires Linux kernel version 4.14 or higher and **a CPU with support for AVX2 instructions**. It also requires at least 4GB of RAM and 8GB of free disk space.
