### ISSUE TITLE
Update the download links for rpk

### ISSUE THREAD

**Issue by JakeSCahill** [redpanda-data/documentation#934]
### Describe the Issue

The filenames for the rpk packages have changed from `rpk-<os>-<arch>.zip` to `rpk_<version>_<os>_<arch>.tar.gz`.

Due to this change, the current rpk installation docs don't work.

See the [latest release](https://github.com/redpanda-data/redpanda/releases/tag/v22.3.6) for the new filenames.

**Note:** The Linux package is currently missing. Monitor this issue for updates: https://github.com/redpanda-data/redpanda/pull/7728

### Updates to existing documentation

https://docs.redpanda.com/docs/platform/quickstart/quick-start-macos/
https://docs.redpanda.com/docs/platform/quickstart/rpk-install/

@Deflaimun this affects your PR to single-source the rpk install docs: #910

**Comment by ivotron** [comment]
this won't be needed after https://github.com/redpanda-data/redpanda/pull/7728 gets merged. sorry for the confusion
