### ISSUE TITLE
Add remote delete details to tiered storage docs

### ISSUE THREAD

**Issue by vuldin** [redpanda-data/documentation#935]
### Describe the Issue

`redpanda.remote.delete` is important in the context of tiered storage but it isn't mentioned in the docs. 

### Updates to existing documentation

https://docs.redpanda.com/docs/platform/data-management/tiered-storage/

### New feature or content gap requests

Internal slack discussion: https://redpandadata.slack.com/archives/C02BDN76HUK/p1670944454375579?thread_ts=1670883030.735509&cid=C02BDN76HUK

**Comment by jcsp** [comment]
This is a dupe of https://github.com/redpanda-data/documentation/issues/717
