### ISSUE TITLE
Create API reference docs (OpenAPI/Swagger) within Redpanda docs 

### ISSUE THREAD

**Issue by shorgi** [redpanda-data/documentation#948]
### Describe the Issue

Currently, API reference docs for Redpanda APIs link to external sites. For example, [schema registry](https://docs.redpanda.com/docs/platform/reference/schema-registry-api/) links to SwaggerHub. 

For a better customer experience, create API reference docs within Redpanda docs.

### Updates to existing documentation

At minimum, [schema registry APIs](https://docs.redpanda.com/docs/platform/reference/schema-registry-api/).

**Comment by JakeSCahill** [comment]
Possible duplicate of #224

**Comment by shorgi** [comment]
Closed, duplicate of #224
