### ISSUE TITLE
Transformations

### ISSUE THREAD

**Issue by coral-waters** [redpanda-data/documentation#95]
Need doc on transformations, including examples. This came about from discussion with Kyle in #jepsen. Part of it is written here: 
https://docs.google.com/document/d/10KjYkN7Yabg-ZPQzSWo3n0UyKKeSeWw7g-YFPLWDg7I/edit#

**Comment by Deflaimun** [comment]
Closed as completed
https://docs.redpanda.com/docs/labs/data-transform/
