### ISSUE TITLE
Move cloud_storage* properties from Tuning Properties to Cluster Config Properties

### ISSUE THREAD

**Issue by AnneLeeperRP** [redpanda-data/documentation#954]
### Describe the Issue

Two cloud storage properties were mistakenly placed in the Tuning Properties table. These belong in Cluster Configuration Properties.

### Updates to existing documentation

Remove `cloud_storage_enable_remote_read` and `cloud_storage_enable_remote_write` from the [Tunable Configuration Properties](https://docs.redpanda.com/docs/platform/reference/tunable-properties/) page.

Add these properties to the [Cloud Storage section](https://docs.redpanda.com/docs/platform/reference/cluster-properties/#cloud-storage) of the Cluster Configuration Properties page.

**Comment by shorgi** [comment]
Won't fix, because verified in source that these properties are still tunable (see https://github.com/redpanda-data/redpanda/blob/dev/src/v/config/configuration.cc#L988, https://github.com/redpanda-data/redpanda/blob/dev/src/v/config/configuration.cc#L994).
