### ISSUE TITLE
cloud: data_cluster vs redpanda_cluster

### ISSUE THREAD

**Issue by coral-waters** [redpanda-data/documentation#96]
Conversation from Slack: 
![image](https://user-images.githubusercontent.com/95656677/151023686-e4535e2e-5763-4f7d-a8a7-c1010d5f09de.png)

**Comment by Feediver1** [comment]
Good update for upcoming Redpanda glossary @micheleRP

**Comment by micheleRP** [comment]
Hi @JakeSCahill. This issue is over a year old & I don't see "data-cluster" or "data_cluster" in our doc. Are you familiar with this with the operator? Or do you know this description for data-cluster is the same with the new operator?

**Comment by micheleRP** [comment]
Hi @daisukebe! This issue is very old, and I don't see anything in our current doc about data clusters. Do we still use this terminology, and could you point me to an area of the doc that needs clarification? Thanks very much!

**Comment by daisukebe** [comment]
Given the cloud deployment is fully managed now, I don't think we need expose / explain the terminology for end users. So, I'm good to close this.

**Comment by micheleRP** [comment]
Thanks, @daisukebe! Closing, as no longer an issue.
