### ISSUE TITLE
Question regarding /metrics and /public_metrics clarification

### ISSUE THREAD

**Issue by WesWWagner** [redpanda-data/documentation#967]
### Describe the Issue
The new /public_metrics endpoint that was added in 22.2 is not properly documented to indicate whether /metrics is still a superset of all metrics, or if there are metrics in public_metrics that do not exist in /metrics and if it is necessary to scrape both.

### Updates to existing documentation
Please clarify the text to indicate whether /metrics is a superset or not

### Additional notes

![image](https://user-images.githubusercontent.com/3193795/209002606-d8e66a1b-384e-4677-b939-67b93f2159cc.png)

**Comment by Feediver1** [comment]
@shorgi  This needs to be fixed in both the 22.2 and 22.3 docs.

**Comment by shorgi** [comment]
Will resolve after #140 is approved/merged.
