### ISSUE TITLE
1Q 2023: Document Creating a BYOC Cluster on GCP

### ISSUE THREAD

**Issue by jrkinley** [redpanda-data/documentation#988]
Create a GCP specific version of this document: https://docs.redpanda.com/docs/cloud/create-byoc-cluster-aws/

**Comment by Feediver1** [comment]
@tcoupland @bpraseed Can you please update this ticket with the specific guidance that @AnneLeeperRP needs to work on this feature doc? Is the feature implemented/rolled out already?

**Comment by Feediver1** [comment]
Lack of doc for this feature is preventing a customer deployment, so high priority.

**Comment by jrkinley** [comment]
@Feediver1 and @AnneLeeperRP I have a draft for this, so I'll send a PR later today.

**Comment by Feediver1** [comment]
@jrkinley created this content
